/**
 * Worker entry (wrangler "main"). Generic API routes call the API worker directly, avoiding an extra Next.js
 * request pipeline. Routes that move whole files also stream R2 bodies natively instead of copying them through
 * Next's Node.js response pipeline, which spends CPU in proportion to the file size. Pages and API routes with
 * custom Next.js behavior still use OpenNext.
 */
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
import openNextWorker from "./.open-next/worker.js";
import apiWorker, { type Env } from "./worker/index";

const FILE_ROUTES: Array<{ methods: string[]; pattern: RegExp }> = [
  { methods: ["GET", "HEAD"], pattern: /^\/api\/material-catalog\/[^/]+\/(download|view)\/?$/ },
  { methods: ["GET", "HEAD"], pattern: /^\/api\/material-anki\/[^/]+\/download\/?$/ },
  { methods: ["GET", "HEAD"], pattern: /^\/api\/material-submissions\/[^/]+\/files\/[^/]+\/?$/ },
  { methods: ["PUT"], pattern: /^\/api\/material-uploads\/[^/]+\/parts\/\d+\/?$/ },
];

export function isFileRoute(method: string, pathname: string): boolean {
  return FILE_ROUTES.some((route) => route.methods.includes(method) && route.pattern.test(pathname));
}

function isDirectApiRoute(method: string, pathname: string): boolean {
  return ["GET", "POST", "PUT", "PATCH", "DELETE"].includes(method)
    && pathname.startsWith("/api/")
    // This route adds statistics to the API response in its Next.js handler.
    && !/^\/api\/quizzes\/progress\/?$/.test(pathname);
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const pathname = new URL(request.url).pathname;
    // Question files are fetched internally through ASSETS after API authentication.
    // Direct URLs never expose a file, including to signed-in users.
    if (pathname === "/__private_quiz" || pathname.startsWith("/__private_quiz/")) {
      return new Response("Not found", { status: 404, headers: { "cache-control": "private, no-store" } });
    }
    if (isFileRoute(request.method, pathname) || isDirectApiRoute(request.method, pathname)) {
      return apiWorker.fetch(request, env, ctx);
    }
    return (openNextWorker as ExportedHandler<Env>).fetch!(request as Request<unknown, IncomingRequestCfProperties>, env, ctx);
  },
} satisfies ExportedHandler<Env>;
