/**
 * Worker entry (wrangler "main"). Everything goes to the OpenNext handler, except the routes that move whole
 * files: those call the API worker directly, so R2 bodies stream natively instead of being copied chunk by chunk
 * through Next's Node.js response pipeline, which spends CPU in proportion to the file size and made large PDFs
 * fail with "Worker exceeded resource limits" (error 1102).
 */
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
import openNextWorker from "./.open-next/worker.js";
import apiWorker, { type Env } from "./worker/index";

const FILE_ROUTES: Array<{ methods: string[]; pattern: RegExp }> = [
  { methods: ["GET", "HEAD"], pattern: /^\/api\/material-catalog\/[^/]+\/(download|view)\/?$/ },
  { methods: ["GET", "HEAD"], pattern: /^\/api\/material-anki\/[^/]+\/download\/?$/ },
  { methods: ["GET", "HEAD"], pattern: /^\/api\/material-submissions\/[^/]+\/files\/[^/]+\/?$/ },
  { methods: ["PUT"], pattern: /^\/api\/material-uploads\/[^/]+\/parts\/\d+\/?$/ },
];

export function isFileRoute(method: string, pathname: string): boolean {
  return FILE_ROUTES.some((route) => route.methods.includes(method) && route.pattern.test(pathname));
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    if (isFileRoute(request.method, new URL(request.url).pathname)) return apiWorker.fetch(request, env, ctx);
    return (openNextWorker as ExportedHandler<Env>).fetch!(request as Request<unknown, IncomingRequestCfProperties>, env, ctx);
  },
} satisfies ExportedHandler<Env>;
