-- Recortes da bibliografia aconselhada no sumário AT6 (Gray 42, Nolte 7, Lippincott 2), associados à aula AT6.
-- Páginas conferidas com o sumário oficial 2026/27; ficheiros carregados e verificados no R2 antes desta migration.

INSERT OR IGNORE INTO material_catalog (id, curricular_unit_id, lesson_id, material_kind, bibliography_format, title, description, file_name, mime_type, storage_backend, storage_key, storage_state, byte_size, checksum_sha256, verification_status, publication_status, source_id, page_note, version_group, version_number, is_recommended, created_at, updated_at) SELECT 'material-biblio-at6-gray42', cu.id, 'lesson-neuro-at6', 'bibliography', 'excerpt', 'Gray’s Anatomy — AT6 · pp. 275–277, 390–391, 517–527.e1, 612, 692.e1–693.e1', 'Recorte da bibliografia aconselhada no sumário AT6.', 'AT06_Gray42_recorte.pdf', 'application/pdf', 'r2', 'materials/neuroanatomia/bibliografia/recortes/AT06_Gray42_recorte.pdf', 'ready', 5271625, 'd077feb262120f07361c0f4b3ce539798c06fac0c69397607b633bf72f1746de', 'verified', 'published', 'source-gray-42', 'Desenvolvimento dos nervos cranianos (tabela 17.1, fig. 17.7); organização funcional dos pares cranianos (tabela 24.1); nervo I, bolbo, trato e córtex olfativos; placa crivosa; epitélio olfativo.', 'biblio-at6-gray42', 1, 1, unixepoch() * 1000, unixepoch() * 1000 FROM curricular_units cu WHERE cu.code = 'NEURO' AND cu.active = 1;
INSERT OR IGNORE INTO material_catalog_lessons (material_id, lesson_id, relevance, sort_order) SELECT 'material-biblio-at6-gray42', 'lesson-neuro-at6', 'primary', 1 WHERE EXISTS (SELECT 1 FROM material_catalog WHERE id = 'material-biblio-at6-gray42') AND EXISTS (SELECT 1 FROM material_lessons WHERE id = 'lesson-neuro-at6');
INSERT OR IGNORE INTO material_catalog (id, curricular_unit_id, lesson_id, material_kind, bibliography_format, title, description, file_name, mime_type, storage_backend, storage_key, storage_state, byte_size, checksum_sha256, verification_status, publication_status, source_id, page_note, version_group, version_number, is_recommended, created_at, updated_at) SELECT 'material-biblio-at6-nolte7', cu.id, 'lesson-neuro-at6', 'bibliography', 'excerpt', 'The Human Brain — AT6 · pp. 301–305, 329–330, 336–345', 'Recorte da bibliografia aconselhada no sumário AT6.', 'AT06_Nolte7_recorte.pdf', 'application/pdf', 'r2', 'materials/neuroanatomia/bibliografia/recortes/AT06_Nolte7_recorte.pdf', 'ready', 37101407, '5cc7374ed22d0f1a201379ccdc62f7ec82488943e016bdf406693341c0d9bc25', 'verified', 'published', 'source-nolte-7', 'Organização geral dos nervos cranianos e dos seus núcleos; introdução aos sentidos químicos; nervo olfativo, bolbo, projeções corticais e função olfativa.', 'biblio-at6-nolte7', 1, 1, unixepoch() * 1000, unixepoch() * 1000 FROM curricular_units cu WHERE cu.code = 'NEURO' AND cu.active = 1;
INSERT OR IGNORE INTO material_catalog_lessons (material_id, lesson_id, relevance, sort_order) SELECT 'material-biblio-at6-nolte7', 'lesson-neuro-at6', 'primary', 2 WHERE EXISTS (SELECT 1 FROM material_catalog WHERE id = 'material-biblio-at6-nolte7') AND EXISTS (SELECT 1 FROM material_lessons WHERE id = 'lesson-neuro-at6');
INSERT OR IGNORE INTO material_catalog (id, curricular_unit_id, lesson_id, material_kind, bibliography_format, title, description, file_name, mime_type, storage_backend, storage_key, storage_state, byte_size, checksum_sha256, verification_status, publication_status, source_id, page_note, version_group, version_number, is_recommended, created_at, updated_at) SELECT 'material-biblio-at6-lippincott2', cu.id, 'lesson-neuro-at6', 'bibliography', 'excerpt', 'Lippincott Illustrated Reviews: Neuroscience — AT6 · pp. 109–120, 425–429', 'Recorte da bibliografia aconselhada no sumário AT6.', 'AT06_Lippincott2_recorte.pdf', 'application/pdf', 'r2', 'materials/neuroanatomia/bibliografia/recortes/AT06_Lippincott2_recorte.pdf', 'ready', 6932447, '5e54d16de824d9e4ab9df9613cd2d370c77d2e1157c0e9fc42cb85ae80fdea27', 'verified', 'published', 'source-lippincott-2', 'Capítulo 6: núcleos dos nervos cranianos e modalidades (tabela 6.1); capítulo 21: olfato e via olfativa.', 'biblio-at6-lippincott2', 1, 1, unixepoch() * 1000, unixepoch() * 1000 FROM curricular_units cu WHERE cu.code = 'NEURO' AND cu.active = 1;
INSERT OR IGNORE INTO material_catalog_lessons (material_id, lesson_id, relevance, sort_order) SELECT 'material-biblio-at6-lippincott2', 'lesson-neuro-at6', 'primary', 3 WHERE EXISTS (SELECT 1 FROM material_catalog WHERE id = 'material-biblio-at6-lippincott2') AND EXISTS (SELECT 1 FROM material_lessons WHERE id = 'lesson-neuro-at6');
