-- Recortes exatos da bibliografia aconselhada nos sumários 2026/27 de AT6 e AP4 (só as páginas indicadas).
-- Ficheiros carregados e verificados no R2 antes desta migration.

INSERT OR IGNORE INTO material_sources (id, title, author, edition, citation, created_at, updated_at) VALUES ('source-nolte-6', 'The Human Brain', 'John Nolte', '6.ª edição', 'The Human Brain, 6th edition', unixepoch() * 1000, unixepoch() * 1000);

-- AT6 · Gray 42: apenas pp. 275–277 (tabela 17.1, fig. 17.7) e 390–391 (tabela 24.1).
UPDATE material_catalog SET title = 'Gray’s Anatomy — AT6 · pp. 275–277, 390–391', page_note = 'Tabela 17.1 (p. 275), fig. 17.7 (p. 277) e tabela 24.1 (pp. 390–391).', file_name = 'AT06_Gray42_recorte.pdf', storage_key = 'materials/neuroanatomia/bibliografia/recortes/2026-27/AT06_Gray42_recorte.pdf', byte_size = 886257, checksum_sha256 = 'c9823b2e57611221f92cc689b52cbf714527497f305c395a21538e325d3c95f6', updated_at = unixepoch() * 1000 WHERE id = 'material-biblio-at6-gray42';
-- AT6 · Nolte: o sumário cita a 6.ª edição; o recorte da 7.ª é arquivado.
UPDATE material_catalog SET publication_status = 'archived', updated_at = unixepoch() * 1000 WHERE id = 'material-biblio-at6-nolte7';

INSERT OR IGNORE INTO material_catalog (id, curricular_unit_id, lesson_id, material_kind, bibliography_format, title, description, file_name, mime_type, storage_backend, storage_key, storage_state, byte_size, checksum_sha256, verification_status, publication_status, source_id, page_note, version_group, version_number, is_recommended, created_at, updated_at) SELECT 'material-biblio-at6-nolte6', cu.id, 'lesson-neuro-at6', 'bibliography', 'excerpt', 'The Human Brain — AT6 · pp. 295–299, 330–339', 'Recorte da bibliografia aconselhada no sumário AT6.', 'AT06_Nolte6_recorte.pdf', 'application/pdf', 'r2', 'materials/neuroanatomia/bibliografia/recortes/2026-27/AT06_Nolte6_recorte.pdf', 'ready', 2001661, 'b09d86c491b85be7029331bb904b1b6f4d05345e937cb547c792153e0a5fd284', 'verified', 'published', 'source-nolte-6', 'Nervos cranianos e seus núcleos (pp. 295–299); sentidos químicos e via olfativa (pp. 330–339).', 'biblio-at6-nolte6', 1, 1, unixepoch() * 1000, unixepoch() * 1000 FROM curricular_units cu WHERE cu.code = 'NEURO' AND cu.active = 1;
INSERT OR IGNORE INTO material_catalog_lessons (material_id, lesson_id, relevance, sort_order) SELECT 'material-biblio-at6-nolte6', 'lesson-neuro-at6', 'primary', 2 WHERE EXISTS (SELECT 1 FROM material_catalog WHERE id = 'material-biblio-at6-nolte6') AND EXISTS (SELECT 1 FROM material_lessons WHERE id = 'lesson-neuro-at6');
INSERT OR IGNORE INTO material_catalog (id, curricular_unit_id, lesson_id, material_kind, bibliography_format, title, description, file_name, mime_type, storage_backend, storage_key, storage_state, byte_size, checksum_sha256, verification_status, publication_status, source_id, page_note, version_group, version_number, is_recommended, created_at, updated_at) SELECT 'material-biblio-ap4-gray42', cu.id, 'lesson-neuro-ap4', 'bibliography', 'excerpt', 'Gray’s Anatomy — AP4 · pp. 391, 450, 453–455, 630–633', 'Recorte da bibliografia aconselhada no sumário AP4.', 'AP04_Gray42_recorte.pdf', 'application/pdf', 'r2', 'materials/neuroanatomia/bibliografia/recortes/2026-27/AP04_Gray42_recorte.pdf', 'ready', 763758, '5252146177cb86a3dcfc6cd14a4261d292f5a241bb9a81d01aa35a47e57ed1ac', 'verified', 'published', 'source-gray-42', 'Tabela 24.1 (p. 391); nervo trigémio: núcleos e raízes (pp. 450, 453–455); face: divisões do trigémio e ramos do facial (pp. 630–633).', 'biblio-ap4-gray42', 1, 1, unixepoch() * 1000, unixepoch() * 1000 FROM curricular_units cu WHERE cu.code = 'NEURO' AND cu.active = 1;
INSERT OR IGNORE INTO material_catalog_lessons (material_id, lesson_id, relevance, sort_order) SELECT 'material-biblio-ap4-gray42', 'lesson-neuro-ap4', 'primary', 1 WHERE EXISTS (SELECT 1 FROM material_catalog WHERE id = 'material-biblio-ap4-gray42') AND EXISTS (SELECT 1 FROM material_lessons WHERE id = 'lesson-neuro-ap4');
INSERT OR IGNORE INTO material_catalog (id, curricular_unit_id, lesson_id, material_kind, bibliography_format, title, description, file_name, mime_type, storage_backend, storage_key, storage_state, byte_size, checksum_sha256, verification_status, publication_status, source_id, page_note, version_group, version_number, is_recommended, created_at, updated_at) SELECT 'material-biblio-ap4-nolte6', cu.id, 'lesson-neuro-ap4', 'bibliography', 'excerpt', 'The Human Brain — AP4 · pp. 295–298, 306–316', 'Recorte da bibliografia aconselhada no sumário AP4.', 'AP04_Nolte6_recorte.pdf', 'application/pdf', 'r2', 'materials/neuroanatomia/bibliografia/recortes/2026-27/AP04_Nolte6_recorte.pdf', 'ready', 1024896, '6ee359f867be15b8d00ac5ee70500e5f1192a9997f7a4fbc15d238359446798d', 'verified', 'published', 'source-nolte-6', 'Nervos cranianos e seus núcleos (pp. 295–298); nervos trigémio e facial (pp. 306–316).', 'biblio-ap4-nolte6', 1, 1, unixepoch() * 1000, unixepoch() * 1000 FROM curricular_units cu WHERE cu.code = 'NEURO' AND cu.active = 1;
INSERT OR IGNORE INTO material_catalog_lessons (material_id, lesson_id, relevance, sort_order) SELECT 'material-biblio-ap4-nolte6', 'lesson-neuro-ap4', 'primary', 2 WHERE EXISTS (SELECT 1 FROM material_catalog WHERE id = 'material-biblio-ap4-nolte6') AND EXISTS (SELECT 1 FROM material_lessons WHERE id = 'lesson-neuro-ap4');
