-- Tradução revista especificamente para AP3; preserva o recorte original.
-- Aplicar apenas após confirmar o objeto privado R2 pelo tamanho e SHA-256.
INSERT OR IGNORE INTO material_catalog (
  id, curricular_unit_id, lesson_id, material_kind, bibliography_format,
  title, description, file_name, mime_type, storage_backend, storage_key,
  storage_state, byte_size, checksum_sha256, verification_status,
  publication_status, public_access, source_id, page_note, version_group,
  version_number, is_recommended, created_at, updated_at
)
SELECT
  'material-biblio-2627-ap03-lippincott2-translation', cu.id,
  'lesson-neuro-ap3', 'bibliography', 'translation',
  'Lippincott Illustrated Reviews: Neuroscience — AP3 · Tradução',
  'Bibliografia traduzida para AP3 — Bolbo, protuberância e mesencéfalo. 27 páginas e 14 figuras traduzidas.',
  'AP3_Lippincott_Bibliografia_Traduzida_2026-09-26.pdf', 'application/pdf', 'r2',
  'materials/neuroanatomia/bibliografia/traducoes/2026-27/AP3_Lippincott_Bibliografia_Traduzida_2026-09-26.pdf',
  'ready', 5400969, '9a52db0e543ee810bc942d1c7db609bfa316a318ed7996921395196a79e70a20',
  'verified', 'published', 0, 'source-lippincott-2',
  'pp. 102–109, 123–124, 130–135; inclui as Figuras 6.21 e 6.22 (pp. 121–122) por remissão.',
  'biblio-2627-ap03-lippincott2-translation', 1, 1,
  unixepoch() * 1000, unixepoch() * 1000
FROM curricular_units cu
WHERE cu.code = 'NEURO' AND cu.active = 1
  AND EXISTS (SELECT 1 FROM material_lessons WHERE id = 'lesson-neuro-ap3')
  AND EXISTS (SELECT 1 FROM material_sources WHERE id = 'source-lippincott-2');

INSERT OR IGNORE INTO material_catalog_lessons (material_id, lesson_id, relevance, sort_order)
SELECT 'material-biblio-2627-ap03-lippincott2-translation', 'lesson-neuro-ap3', 'primary', 0
WHERE EXISTS (SELECT 1 FROM material_catalog WHERE id = 'material-biblio-2627-ap03-lippincott2-translation');

INSERT OR IGNORE INTO material_catalog (id,curricular_unit_id,lesson_id,material_kind,bibliography_format,title,description,file_name,mime_type,storage_backend,storage_key,storage_state,byte_size,checksum_sha256,verification_status,publication_status,public_access,source_id,page_note,version_group,version_number,is_recommended,created_at,updated_at) SELECT 'material-biblio-2627-ap1-gray-translation',cu.id,'lesson-neuro-ap1','bibliography','translation','Gray — AP1 · Tradução','cap. 34, pp. 558–568; cap. 36, pp. 609–614. Bibliografia indicada no sumário da AP1 (páginas da 41.ª edição); esta tradução usa a 42.ª edição, cujos intervalos de páginas não coincidem exatamente com os da 41.ª.','AP1_Gray_Bibliografia_Traduzida_2026-09-24.pdf','application/pdf','r2','materials/neuroanatomia/bibliografia/traducoes/2026-27/AP1_Gray_Bibliografia_Traduzida_2026-09-24.pdf','ready',2195071,'03fbf2557078035ae4a7aa2152e3c6f959192556dbdc88437f033b87024b75e4','verified','published',0,'source-gray-42','cap. 34, pp. 558–568; cap. 36, pp. 609–614. Bibliografia indicada no sumário da AP1 (páginas da 41.ª edição); esta tradução usa a 42.ª edição, cujos intervalos de páginas não coincidem exatamente com os da 41.ª.','material-biblio-2627-ap1-gray-translation',1,1,unixepoch()*1000,unixepoch()*1000 FROM curricular_units cu WHERE cu.code='NEURO' AND cu.active=1 AND EXISTS (SELECT 1 FROM material_lessons WHERE id='lesson-neuro-ap1') AND EXISTS (SELECT 1 FROM material_sources WHERE id='source-gray-42');
INSERT OR IGNORE INTO material_catalog_lessons (material_id,lesson_id,relevance,sort_order) SELECT 'material-biblio-2627-ap1-gray-translation','lesson-neuro-ap1','primary',0 WHERE EXISTS (SELECT 1 FROM material_catalog WHERE id='material-biblio-2627-ap1-gray-translation');

INSERT OR IGNORE INTO material_catalog (id,curricular_unit_id,lesson_id,material_kind,bibliography_format,title,description,file_name,mime_type,storage_backend,storage_key,storage_state,byte_size,checksum_sha256,verification_status,publication_status,public_access,source_id,page_note,version_group,version_number,is_recommended,created_at,updated_at) SELECT 'material-biblio-2627-ap1-lippincott-translation',cu.id,'lesson-neuro-ap1','bibliography','translation','Lippincott — AP1 · Tradução','cap. 1, pp. 1–2; cap. 2, pp. 24–28 e 40–42; cap. 3, pp. 48–49; cap. 4, pp. 62–68. Leitura complementar: o sumário da AP1 indica apenas páginas do Gray; estas páginas foram escolhidas por correspondência com os temas da aula.','AP1_Lippincott_Bibliografia_Traduzida_2026-09-24.pdf','application/pdf','r2','materials/neuroanatomia/bibliografia/traducoes/2026-27/AP1_Lippincott_Bibliografia_Traduzida_2026-09-24.pdf','ready',1644783,'a730318a40f2563b89d16fd2a272be0e4756e101400cff1c492bee9d45936147','verified','published',0,'source-lippincott-2','cap. 1, pp. 1–2; cap. 2, pp. 24–28 e 40–42; cap. 3, pp. 48–49; cap. 4, pp. 62–68. Leitura complementar: o sumário da AP1 indica apenas páginas do Gray; estas páginas foram escolhidas por correspondência com os temas da aula.','material-biblio-2627-ap1-lippincott-translation',1,1,unixepoch()*1000,unixepoch()*1000 FROM curricular_units cu WHERE cu.code='NEURO' AND cu.active=1 AND EXISTS (SELECT 1 FROM material_lessons WHERE id='lesson-neuro-ap1') AND EXISTS (SELECT 1 FROM material_sources WHERE id='source-lippincott-2');
INSERT OR IGNORE INTO material_catalog_lessons (material_id,lesson_id,relevance,sort_order) SELECT 'material-biblio-2627-ap1-lippincott-translation','lesson-neuro-ap1','complementary',0 WHERE EXISTS (SELECT 1 FROM material_catalog WHERE id='material-biblio-2627-ap1-lippincott-translation');

INSERT OR IGNORE INTO material_catalog (id,curricular_unit_id,lesson_id,material_kind,bibliography_format,title,description,file_name,mime_type,storage_backend,storage_key,storage_state,byte_size,checksum_sha256,verification_status,publication_status,public_access,source_id,page_note,version_group,version_number,is_recommended,created_at,updated_at) SELECT 'material-biblio-2627-ap1-nolte-translation',cu.id,'lesson-neuro-ap1','bibliography','translation','Nolte — AP1 · Tradução','cap. 1, pp. 1–10; cap. 3, pp. 57–58 e 68–69; cap. 4, pp. 84–96; cap. 10, pp. 234–235. Leitura complementar: o sumário da AP1 indica apenas páginas do Gray; estas páginas foram escolhidas por correspondência com os temas da aula.','AP1_Nolte_Bibliografia_Traduzida_2026-09-24.pdf','application/pdf','r2','materials/neuroanatomia/bibliografia/traducoes/2026-27/AP1_Nolte_Bibliografia_Traduzida_2026-09-24.pdf','ready',1517030,'b257ccdbe95b44f8287cf7fe452e0e37f0af2e5cc7d6e4ef2755843b2010e0a9','verified','published',0,'source-nolte-7','cap. 1, pp. 1–10; cap. 3, pp. 57–58 e 68–69; cap. 4, pp. 84–96; cap. 10, pp. 234–235. Leitura complementar: o sumário da AP1 indica apenas páginas do Gray; estas páginas foram escolhidas por correspondência com os temas da aula.','material-biblio-2627-ap1-nolte-translation',1,1,unixepoch()*1000,unixepoch()*1000 FROM curricular_units cu WHERE cu.code='NEURO' AND cu.active=1 AND EXISTS (SELECT 1 FROM material_lessons WHERE id='lesson-neuro-ap1') AND EXISTS (SELECT 1 FROM material_sources WHERE id='source-nolte-7');
INSERT OR IGNORE INTO material_catalog_lessons (material_id,lesson_id,relevance,sort_order) SELECT 'material-biblio-2627-ap1-nolte-translation','lesson-neuro-ap1','complementary',0 WHERE EXISTS (SELECT 1 FROM material_catalog WHERE id='material-biblio-2627-ap1-nolte-translation');

INSERT OR IGNORE INTO material_catalog (id,curricular_unit_id,lesson_id,material_kind,bibliography_format,title,description,file_name,mime_type,storage_backend,storage_key,storage_state,byte_size,checksum_sha256,verification_status,publication_status,public_access,source_id,page_note,version_group,version_number,is_recommended,created_at,updated_at) SELECT 'material-biblio-2627-ap2-gray-translation',cu.id,'lesson-neuro-ap2','bibliography','translation','Gray — AP2 · Tradução','cap. 47, pp. 856–861 e 867. Leitura complementar («Para saber mais») do sumário da AP2, que cita o Gray 41.ª ed., pp. 762–768; esta tradução usa a 42.ª edição. As referências principais da AP2 são o Nolte e o Lippincott.','AP2_Gray_Bibliografia_Traduzida_2026-09-25.pdf','application/pdf','r2','materials/neuroanatomia/bibliografia/traducoes/2026-27/AP2_Gray_Bibliografia_Traduzida_2026-09-25.pdf','ready',1590493,'8b88635ec481ae50db717b61b849b5421d6beb80c53a3160cb763cd6c45ab30b','verified','published',0,'source-gray-42','cap. 47, pp. 856–861 e 867. Leitura complementar («Para saber mais») do sumário da AP2, que cita o Gray 41.ª ed., pp. 762–768; esta tradução usa a 42.ª edição. As referências principais da AP2 são o Nolte e o Lippincott.','material-biblio-2627-ap2-gray-translation',1,1,unixepoch()*1000,unixepoch()*1000 FROM curricular_units cu WHERE cu.code='NEURO' AND cu.active=1 AND EXISTS (SELECT 1 FROM material_lessons WHERE id='lesson-neuro-ap2') AND EXISTS (SELECT 1 FROM material_sources WHERE id='source-gray-42');
INSERT OR IGNORE INTO material_catalog_lessons (material_id,lesson_id,relevance,sort_order) SELECT 'material-biblio-2627-ap2-gray-translation','lesson-neuro-ap2','complementary',0 WHERE EXISTS (SELECT 1 FROM material_catalog WHERE id='material-biblio-2627-ap2-gray-translation');

INSERT OR IGNORE INTO material_catalog (id,curricular_unit_id,lesson_id,material_kind,bibliography_format,title,description,file_name,mime_type,storage_backend,storage_key,storage_state,byte_size,checksum_sha256,verification_status,publication_status,public_access,source_id,page_note,version_group,version_number,is_recommended,created_at,updated_at) SELECT 'material-biblio-2627-ap2-nolte-translation',cu.id,'lesson-neuro-ap2','bibliography','translation','Nolte — AP2 · Tradução','pp. 233–244. Bibliografia aconselhada no sumário da AP2.','AP2_Nolte_Bibliografia_Traduzida_2026-09-25.pdf','application/pdf','r2','materials/neuroanatomia/bibliografia/traducoes/2026-27/AP2_Nolte_Bibliografia_Traduzida_2026-09-25.pdf','ready',3211650,'5cc3aa992de2677e97361521af2c8c43a70d6c096f347e85c0117ef6ad1b9206','verified','published',0,'source-nolte-7','pp. 233–244. Bibliografia aconselhada no sumário da AP2.','material-biblio-2627-ap2-nolte-translation',1,1,unixepoch()*1000,unixepoch()*1000 FROM curricular_units cu WHERE cu.code='NEURO' AND cu.active=1 AND EXISTS (SELECT 1 FROM material_lessons WHERE id='lesson-neuro-ap2') AND EXISTS (SELECT 1 FROM material_sources WHERE id='source-nolte-7');
INSERT OR IGNORE INTO material_catalog_lessons (material_id,lesson_id,relevance,sort_order) SELECT 'material-biblio-2627-ap2-nolte-translation','lesson-neuro-ap2','primary',0 WHERE EXISTS (SELECT 1 FROM material_catalog WHERE id='material-biblio-2627-ap2-nolte-translation');


