-- Publish the user-supplied Neuroanatomia pack after R2 checksum verification.
-- Archive the previous editions while preserving their records and references.
UPDATE material_anki_decks SET publication_status='archived',updated_at=unixepoch()*1000
WHERE id IN ('anki-neuro-essential','anki-neuro-complete');

INSERT OR IGNORE INTO material_anki_decks
(id,curricular_unit_id,title,variant,description,file_name,mime_type,storage_backend,storage_key,storage_state,byte_size,checksum_sha256,card_count,media_count,source_file_name,publication_status,public_access,created_at,updated_at)
SELECT 'anki-neuro-at1-at21-ap1-ap13',cu.id,'Neuroanatomia · AT1–AT21 e AP1–AP13','custom','Pack de Neuroanatomia com 3079 cartões de resposta curta e identificação de imagens, organizado por AT1–AT21 e AP1–AP13.','Neuroanatomia_AT1-AT21_AP1-AP13.apkg','application/apkg','r2','materials/neuroanatomia/anki/643d99223fb552e7f5925d681d08bb856d14f759f240fa6a2773f4f914eae1a6.apkg','ready',289648634,'643d99223fb552e7f5925d681d08bb856d14f759f240fa6a2773f4f914eae1a6',3079,646,'Neuroanatomia_AT1-AT21_AP1-AP13.apkg','published',0,unixepoch()*1000,unixepoch()*1000
FROM curricular_units cu WHERE cu.code='NEURO' AND cu.active=1;

-- Add the practical lessons absent from the existing catalogue.
INSERT OR IGNORE INTO material_lessons(id,curricular_unit_id,code,title,lesson_type,sort_order,created_at,updated_at) SELECT 'lesson-neuro-ap6',cu.id,'AP6','Aula prática 6','practical',106,unixepoch()*1000,unixepoch()*1000 FROM curricular_units cu WHERE cu.code='NEURO' AND cu.active=1;
INSERT OR IGNORE INTO material_lessons(id,curricular_unit_id,code,title,lesson_type,sort_order,created_at,updated_at) SELECT 'lesson-neuro-ap8',cu.id,'AP8','Aula prática 8','practical',108,unixepoch()*1000,unixepoch()*1000 FROM curricular_units cu WHERE cu.code='NEURO' AND cu.active=1;
INSERT OR IGNORE INTO material_lessons(id,curricular_unit_id,code,title,lesson_type,sort_order,created_at,updated_at) SELECT 'lesson-neuro-ap9',cu.id,'AP9','Aula prática 9','practical',109,unixepoch()*1000,unixepoch()*1000 FROM curricular_units cu WHERE cu.code='NEURO' AND cu.active=1;
INSERT OR IGNORE INTO material_lessons(id,curricular_unit_id,code,title,lesson_type,sort_order,created_at,updated_at) SELECT 'lesson-neuro-ap11',cu.id,'AP11','Aula prática 11','practical',111,unixepoch()*1000,unixepoch()*1000 FROM curricular_units cu WHERE cu.code='NEURO' AND cu.active=1;
INSERT OR IGNORE INTO material_lessons(id,curricular_unit_id,code,title,lesson_type,sort_order,created_at,updated_at) SELECT 'lesson-neuro-ap12',cu.id,'AP12','Aula prática 12','practical',112,unixepoch()*1000,unixepoch()*1000 FROM curricular_units cu WHERE cu.code='NEURO' AND cu.active=1;

INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,382 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AP1' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,122 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AP2' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,119 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AP3' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,112 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AP4' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,125 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AP5' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,116 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AP6' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,79 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AP7' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,98 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AP8' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,76 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AP9' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,159 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AP10' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,62 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AP11' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,104 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AP12' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,30 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AP13' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,99 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AT1' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,100 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AT2' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,98 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AT3' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,87 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AT4' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,99 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AT5' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,67 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AT6' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,68 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AT7' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,67 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AT8' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,84 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AT9' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,84 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AT10' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,58 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AT11' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,62 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AT12' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,76 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AT13' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,53 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AT14' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,69 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AT15' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,68 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AT16' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,71 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AT17' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,49 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AT18' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,51 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AT19' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,47 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AT20' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');
INSERT OR IGNORE INTO material_anki_deck_lessons(deck_id,lesson_id,card_count) SELECT 'anki-neuro-at1-at21-ap1-ap13',l.id,38 FROM material_lessons l JOIN curricular_units cu ON cu.id=l.curricular_unit_id WHERE cu.code='NEURO' AND l.code='AT21' AND EXISTS(SELECT 1 FROM material_anki_decks WHERE id='anki-neuro-at1-at21-ap1-ap13');

INSERT INTO admin_audit_log(actor_user_id,action,details,created_at)
SELECT id,'materials_anki_published','{"source":"authorized-neuro-anki-2026-10-01","deck":"anki-neuro-at1-at21-ap1-ap13","cards":3079,"archivedEditions":2}',unixepoch()*1000
FROM users WHERE status='active' AND (commission_position='principal_admin' OR role='admin')
AND NOT EXISTS(SELECT 1 FROM admin_audit_log WHERE action='materials_anki_published' AND details LIKE '%authorized-neuro-anki-2026-10-01%')
ORDER BY CASE WHEN commission_position='principal_admin' THEN 0 ELSE 1 END,created_at LIMIT 1;
