-- Sete traduções finais aprovadas. Confirmar objetos R2 privados antes de aplicar.

INSERT OR IGNORE INTO material_catalog (id,curricular_unit_id,lesson_id,material_kind,bibliography_format,title,description,file_name,mime_type,storage_backend,storage_key,storage_state,byte_size,checksum_sha256,verification_status,publication_status,public_access,source_id,page_note,version_group,version_number,is_recommended,created_at,updated_at) SELECT 'material-biblio-2627-ap6-lippincott2-translation',cu.id,'lesson-neuro-ap6','bibliography','translation','Lippincott Illustrated Reviews: Neuroscience — AP6 · Tradução','Bibliografia traduzida para AP6 — Cerebelo. Diencéfalo. Hipófise (AT9, AT10). 95 páginas.','AP6_Lippincott_Bibliografia_Traduzida_2026-10-04.pdf','application/pdf','r2','materials/neuroanatomia/bibliografia/traducoes/2026-27/AP6_Lippincott_Bibliografia_Traduzida_2026-10-04.pdf','ready',13459633,'f7e633368a7989b43fd7fbd84bdd9a8d3134595cacf8473d7500329f802e8e33','verified','published',0,'source-lippincott-2','Lippincott, 2.ª edição: pp. 355–364; pp. 365–373; pp. 293–301; pp. 302–310; pp. 385–395; pp. 396–405','biblio-2627-ap6-lippincott2-translation',1,1,unixepoch()*1000,unixepoch()*1000 FROM curricular_units cu WHERE cu.code='NEURO' AND cu.active=1 AND EXISTS(SELECT 1 FROM material_sources WHERE id='source-lippincott-2') AND EXISTS(SELECT 1 FROM material_lessons WHERE id='lesson-neuro-ap6');

INSERT OR IGNORE INTO material_catalog_lessons(material_id,lesson_id,relevance,sort_order) SELECT 'material-biblio-2627-ap6-lippincott2-translation','lesson-neuro-ap6','primary',0 WHERE EXISTS(SELECT 1 FROM material_catalog WHERE id='material-biblio-2627-ap6-lippincott2-translation');

INSERT OR IGNORE INTO material_catalog (id,curricular_unit_id,lesson_id,material_kind,bibliography_format,title,description,file_name,mime_type,storage_backend,storage_key,storage_state,byte_size,checksum_sha256,verification_status,publication_status,public_access,source_id,page_note,version_group,version_number,is_recommended,created_at,updated_at) SELECT 'material-biblio-2627-ap11-lippincott2-translation',cu.id,'lesson-neuro-ap11','bibliography','translation','Lippincott Illustrated Reviews: Neuroscience — AP11 · Tradução','Bibliografia traduzida para AP11 — Conteúdo orbitário. Nervos óptico, oculomotor, troclear e abducente. Via óptica (AT16, AT17). 91 páginas.','AP11_Lippincott_Bibliografia_Traduzida_2026-10-04.pdf','application/pdf','r2','materials/neuroanatomia/bibliografia/traducoes/2026-27/AP11_Lippincott_Bibliografia_Traduzida_2026-10-04.pdf','ready',12011625,'9f7652cf21f31179ca4b60ff323a0f3fb66d6add8146f6542d93f96d0c72c268','verified','published',0,'source-lippincott-2','Lippincott, 2.ª edição: pp. 161–173; pp. 174–186; pp. 311–322; pp. 323–334','biblio-2627-ap11-lippincott2-translation',1,1,unixepoch()*1000,unixepoch()*1000 FROM curricular_units cu WHERE cu.code='NEURO' AND cu.active=1 AND EXISTS(SELECT 1 FROM material_sources WHERE id='source-lippincott-2') AND EXISTS(SELECT 1 FROM material_lessons WHERE id='lesson-neuro-ap11');

INSERT OR IGNORE INTO material_catalog_lessons(material_id,lesson_id,relevance,sort_order) SELECT 'material-biblio-2627-ap11-lippincott2-translation','lesson-neuro-ap11','primary',0 WHERE EXISTS(SELECT 1 FROM material_catalog WHERE id='material-biblio-2627-ap11-lippincott2-translation');

INSERT OR IGNORE INTO material_catalog (id,curricular_unit_id,lesson_id,material_kind,bibliography_format,title,description,file_name,mime_type,storage_backend,storage_key,storage_state,byte_size,checksum_sha256,verification_status,publication_status,public_access,source_id,page_note,version_group,version_number,is_recommended,created_at,updated_at) SELECT 'material-biblio-2627-ap12-lippincott2-translation',cu.id,'lesson-neuro-ap12','bibliography','translation','Lippincott Illustrated Reviews: Neuroscience — AP12 · Tradução','Bibliografia traduzida para AP12 — Ouvido. Nervo vestibulococlear. Vias acústica e vestibular (AT18). 47 páginas.','AP12_Lippincott_Bibliografia_Traduzida_2026-10-01.pdf','application/pdf','r2','materials/neuroanatomia/bibliografia/traducoes/2026-27/AP12_Lippincott_Bibliografia_Traduzida_2026-10-01.pdf','ready',7848232,'a5377d1ba9eb2e1b4a2c53dd7c304c2f53c629d7b03831160e0f6fac7630ca60','verified','published',0,'source-lippincott-2','Lippincott, 2.ª edição: pp. 214–226; pp. 227–239','biblio-2627-ap12-lippincott2-translation',1,1,unixepoch()*1000,unixepoch()*1000 FROM curricular_units cu WHERE cu.code='NEURO' AND cu.active=1 AND EXISTS(SELECT 1 FROM material_sources WHERE id='source-lippincott-2') AND EXISTS(SELECT 1 FROM material_lessons WHERE id='lesson-neuro-ap12');

INSERT OR IGNORE INTO material_catalog_lessons(material_id,lesson_id,relevance,sort_order) SELECT 'material-biblio-2627-ap12-lippincott2-translation','lesson-neuro-ap12','primary',0 WHERE EXISTS(SELECT 1 FROM material_catalog WHERE id='material-biblio-2627-ap12-lippincott2-translation');

INSERT OR IGNORE INTO material_catalog (id,curricular_unit_id,lesson_id,material_kind,bibliography_format,title,description,file_name,mime_type,storage_backend,storage_key,storage_state,byte_size,checksum_sha256,verification_status,publication_status,public_access,source_id,page_note,version_group,version_number,is_recommended,created_at,updated_at) SELECT 'material-biblio-2627-ap8-lippincott2-translation',cu.id,'lesson-neuro-ap8','bibliography','translation','Lippincott Illustrated Reviews: Neuroscience — AP8 · Tradução','Bibliografia traduzida para AP8 — Telencéfalo II — configuração interna. Sistema límbico. 67 páginas.','AP8_Lippincott_Bibliografia_Traduzida_2026-10-01.pdf','application/pdf','r2','materials/neuroanatomia/bibliografia/traducoes/2026-27/AP8_Lippincott_Bibliografia_Traduzida_2026-10-01.pdf','ready',8286160,'c1cf241c0b12e6843a86aa4670c224a19cb8ca63985b6fe8e83bc2a2d1c5b213','verified','published',0,'source-lippincott-2','Lippincott, 2.ª edição: pp. 406–415; pp. 416–424; pp. 335–344; pp. 345–354','biblio-2627-ap8-lippincott2-translation',1,1,unixepoch()*1000,unixepoch()*1000 FROM curricular_units cu WHERE cu.code='NEURO' AND cu.active=1 AND EXISTS(SELECT 1 FROM material_sources WHERE id='source-lippincott-2') AND EXISTS(SELECT 1 FROM material_lessons WHERE id='lesson-neuro-ap8');

INSERT OR IGNORE INTO material_catalog_lessons(material_id,lesson_id,relevance,sort_order) SELECT 'material-biblio-2627-ap8-lippincott2-translation','lesson-neuro-ap8','primary',0 WHERE EXISTS(SELECT 1 FROM material_catalog WHERE id='material-biblio-2627-ap8-lippincott2-translation');

INSERT OR IGNORE INTO material_catalog (id,curricular_unit_id,lesson_id,material_kind,bibliography_format,title,description,file_name,mime_type,storage_backend,storage_key,storage_state,byte_size,checksum_sha256,verification_status,publication_status,public_access,source_id,page_note,version_group,version_number,is_recommended,created_at,updated_at) SELECT 'material-biblio-2627-ap9-lippincott2-translation',cu.id,'lesson-neuro-ap9','bibliography','translation','Lippincott Illustrated Reviews: Neuroscience — AP9 · Tradução','Bibliografia traduzida para AP9 — Núcleos da base. Sistema ventricular (AT14). 38 páginas.','AP9_Lippincott_Bibliografia_Traduzida_2026-10-01.pdf','application/pdf','r2','materials/neuroanatomia/bibliografia/traducoes/2026-27/AP9_Lippincott_Bibliografia_Traduzida_2026-10-01.pdf','ready',5440710,'873b465832eddd5eabed368557ebea993c1f81b63eec0233ab332f25976164dc','verified','published',0,'source-lippincott-2','Lippincott, 2.ª edição: pp. 335–344; pp. 345–354','biblio-2627-ap9-lippincott2-translation',1,1,unixepoch()*1000,unixepoch()*1000 FROM curricular_units cu WHERE cu.code='NEURO' AND cu.active=1 AND EXISTS(SELECT 1 FROM material_sources WHERE id='source-lippincott-2') AND EXISTS(SELECT 1 FROM material_lessons WHERE id='lesson-neuro-ap9');

INSERT OR IGNORE INTO material_catalog_lessons(material_id,lesson_id,relevance,sort_order) SELECT 'material-biblio-2627-ap9-lippincott2-translation','lesson-neuro-ap9','primary',0 WHERE EXISTS(SELECT 1 FROM material_catalog WHERE id='material-biblio-2627-ap9-lippincott2-translation');

INSERT OR IGNORE INTO material_catalog (id,curricular_unit_id,lesson_id,material_kind,bibliography_format,title,description,file_name,mime_type,storage_backend,storage_key,storage_state,byte_size,checksum_sha256,verification_status,publication_status,public_access,source_id,page_note,version_group,version_number,is_recommended,created_at,updated_at) SELECT 'material-biblio-2627-at20-lippincott2-translation',cu.id,'lesson-neuro-at20','bibliography','translation','Lippincott Illustrated Reviews: Neuroscience — AT20 · Tradução','Bibliografia traduzida para AT20 — Vias aferentes. 63 páginas.','AT20_Lippincott_Bibliografia_Traduzida_2026-10-01.pdf','application/pdf','r2','materials/neuroanatomia/bibliografia/traducoes/2026-27/AT20_Lippincott_Bibliografia_Traduzida_2026-10-01.pdf','ready',8286587,'87b80d95949894cdbb7885d0e18d92e0a751ecdb83100b84a16b1522ec780dc1','verified','published',0,'source-lippincott-2','Lippincott, 2.ª edição: pp. 128–137; pp. 138–146; pp. 438–447; pp. 448–457','biblio-2627-at20-lippincott2-translation',1,1,unixepoch()*1000,unixepoch()*1000 FROM curricular_units cu WHERE cu.code='NEURO' AND cu.active=1 AND EXISTS(SELECT 1 FROM material_sources WHERE id='source-lippincott-2') AND EXISTS(SELECT 1 FROM material_lessons WHERE id='lesson-neuro-at20');

INSERT OR IGNORE INTO material_catalog_lessons(material_id,lesson_id,relevance,sort_order) SELECT 'material-biblio-2627-at20-lippincott2-translation','lesson-neuro-at20','primary',0 WHERE EXISTS(SELECT 1 FROM material_catalog WHERE id='material-biblio-2627-at20-lippincott2-translation');

INSERT OR IGNORE INTO material_catalog (id,curricular_unit_id,lesson_id,material_kind,bibliography_format,title,description,file_name,mime_type,storage_backend,storage_key,storage_state,byte_size,checksum_sha256,verification_status,publication_status,public_access,source_id,page_note,version_group,version_number,is_recommended,created_at,updated_at) SELECT 'material-biblio-2627-at21-lippincott2-translation',cu.id,'lesson-neuro-at21','bibliography','translation','Lippincott Illustrated Reviews: Neuroscience — AT21 · Tradução','Bibliografia traduzida para AT21 — Vias eferentes. 42 páginas.','AT21_Lippincott_Bibliografia_Traduzida_2026-10-02.pdf','application/pdf','r2','materials/neuroanatomia/bibliografia/traducoes/2026-27/AT21_Lippincott_Bibliografia_Traduzida_2026-10-02.pdf','ready',3741815,'8149c59685f72fde49d3f3d081172af62e55c6233b8188c67b998bf81e42499f','verified','published',0,'source-lippincott-2','Lippincott, 2.ª edição: pp. 147–159; pp. 374–383','biblio-2627-at21-lippincott2-translation',1,1,unixepoch()*1000,unixepoch()*1000 FROM curricular_units cu WHERE cu.code='NEURO' AND cu.active=1 AND EXISTS(SELECT 1 FROM material_sources WHERE id='source-lippincott-2') AND EXISTS(SELECT 1 FROM material_lessons WHERE id='lesson-neuro-at21');

INSERT OR IGNORE INTO material_catalog_lessons(material_id,lesson_id,relevance,sort_order) SELECT 'material-biblio-2627-at21-lippincott2-translation','lesson-neuro-at21','primary',0 WHERE EXISTS(SELECT 1 FROM material_catalog WHERE id='material-biblio-2627-at21-lippincott2-translation');

INSERT INTO admin_audit_log(actor_user_id,action,details,created_at) SELECT id,'neuro_translations_published','{"batch":"approved-lippincott-2026-10-08","count":7}',unixepoch()*1000 FROM users WHERE status='active' AND commission_position='principal_admin' AND NOT EXISTS(SELECT 1 FROM admin_audit_log WHERE action='neuro_translations_published' AND details LIKE '%approved-lippincott-2026-10-08%') LIMIT 1;
