"use client";

import { useEffect, useMemo, useState } from "react";
import { Ban, CheckCircle2, Clock3, Save, Search, Settings, ShieldCheck, UserCog, Users } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { useAuth } from "@/components/auth-context";

type Role = "student" | "representative" | "admin";
type Status = "active" | "pending" | "suspended" | "banned";
type User = { id: string; email: string; full_name: string; role: Role; status: Status; status_reason: string | null; status_until: number | null; commission_position: string | null; commission_department: string | null; email_verified_at: number; last_login_at: number | null; created_at: number; updated_at: number };
type Position = { code: string; label: string; authority_level: "supreme" | "core" | "moderator"; rank: number };
type Department = { code: string; label: string; rank: number };
const labels: Record<Status, string> = { active: "Ativo", pending: "Por validar", suspended: "Suspenso", banned: "Banido" };

export function AdminControl() {
  const { user: sessionUser } = useAuth();
  const [users, setUsers] = useState<User[]>([]); const [query, setQuery] = useState(""); const [filter, setFilter] = useState<Status | "all">("all");
  const [maintenance, setMaintenance] = useState(true); const [message, setMessage] = useState(""); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true);
  const [positions, setPositions] = useState<Position[]>([]); const [departments, setDepartments] = useState<Department[]>([]);
  const load = async () => { const [u, s] = await Promise.all([fetch("/api/admin/users", { cache: "no-store" }), fetch("/api/admin/settings", { cache: "no-store" })]); if (u.status === 403) return; const ud = await u.json() as { users: User[]; positions: Position[]; departments: Department[] }; const sd = await s.json() as { maintenanceMode: boolean; maintenanceMessage: string }; setUsers(ud.users); setPositions(ud.positions); setDepartments(ud.departments); setMaintenance(sd.maintenanceMode); setMessage(sd.maintenanceMessage); setLoading(false); };
  // A função inicia I/O antes de atualizar o estado com a resposta.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, []);
  const visible = useMemo(() => users.filter((u) => (filter === "all" || u.status === filter) && `${u.full_name} ${u.email}`.toLowerCase().includes(query.toLowerCase())), [filter, query, users]);
  const updateLocal = (id: string, patch: Partial<User>) => setUsers((all) => all.map((u) => u.id === id ? { ...u, ...patch } : u));
  const saveUser = async (u: User) => { const response = await fetch("/api/admin/users", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: u.id, fullName: u.full_name, role: u.role, status: u.status, reason: u.status_reason, statusUntil: u.status_until, commissionPosition: u.commission_position, commissionDepartment: u.commission_department }) }); const data = await response.json() as { error?: string }; setNotice(response.ok ? `Alterações a ${u.email} guardadas.` : data.error || "Não foi possível guardar."); if (response.ok) void load(); };
  const saveSettings = async () => { const response = await fetch("/api/admin/settings", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ maintenanceMode: maintenance, maintenanceMessage: message }) }); const data = await response.json() as { error?: string }; setNotice(response.ok ? "Configuração da plataforma atualizada." : data.error || "Não foi possível guardar."); };
  if (sessionUser?.role !== "admin") return <main className="auth-loading"><ShieldCheck size={28} /><strong>Acesso reservado a administradores.</strong></main>;
  return <AppShell active="admin" breadcrumb="Controlo administrativo"><div className="admin-heading"><div><span className="eyebrow">Administração</span><h1>Controlo da plataforma</h1><p>Gere acessos, perfis e disponibilidade do Gestor Universitário.</p></div><span className="admin-secure"><ShieldCheck size={17} />Ações auditadas</span></div>
    <section className="admin-stats"><article><Users /><div><strong>{users.length}</strong><span>Utilizadores</span></div></article><article><CheckCircle2 /><div><strong>{users.filter(u=>u.status==='active').length}</strong><span>Ativos</span></div></article><article><Clock3 /><div><strong>{users.filter(u=>u.status==='pending').length}</strong><span>Por validar</span></div></article><article><Ban /><div><strong>{users.filter(u=>['banned','suspended'].includes(u.status)).length}</strong><span>Bloqueados</span></div></article></section>
    <section className="panel admin-settings"><Settings /><div><h2>Disponibilidade do site</h2><p>Os administradores mantêm sempre acesso durante a manutenção.</p></div><label className="switch"><input type="checkbox" checked={maintenance} onChange={e=>setMaintenance(e.target.checked)} /><span>{maintenance ? "Manutenção ativa" : "Site disponível"}</span></label><textarea value={message} onChange={e=>setMessage(e.target.value)} maxLength={500} aria-label="Mensagem de manutenção" /><button className="button button--primary" onClick={()=>void saveSettings()}><Save size={16}/>Guardar</button></section>
    <section className="panel admin-users"><div className="panel__header"><div><span className="eyebrow">Contas</span><h2>Utilizadores e permissões</h2></div><div className="panel-tools"><label className="search-field"><Search size={16}/><input placeholder="Pesquisar nome ou email" value={query} onChange={e=>setQuery(e.target.value)}/></label><select value={filter} onChange={e=>setFilter(e.target.value as Status|'all')}><option value="all">Todos os estados</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div></div>
      {notice && <p className="admin-notice" role="status">{notice}</p>}{loading ? <p className="admin-empty">A carregar utilizadores…</p> : <div className="admin-table-wrap"><table><thead><tr><th>Utilizador</th><th>Perfil</th><th>Cargo CC</th><th>Departamento</th><th>Estado</th><th>Motivo / até</th><th>Último acesso</th><th></th></tr></thead><tbody>{visible.map(u=><tr key={u.id}><td><input className="admin-name" value={u.full_name} onChange={e=>updateLocal(u.id,{full_name:e.target.value})}/><small>{u.email}</small></td><td><select value={u.role} onChange={e=>updateLocal(u.id,{role:e.target.value as Role})}><option value="student">Estudante</option><option value="representative">Representante</option><option value="admin">Administrador</option></select></td><td><select value={u.commission_position||""} onChange={e=>updateLocal(u.id,{commission_position:e.target.value||null})}><option value="">Sem cargo</option>{positions.map(p=><option key={p.code} value={p.code}>{p.label}</option>)}</select></td><td><select value={u.commission_department||""} onChange={e=>updateLocal(u.id,{commission_department:e.target.value||null})}><option value="">Sem departamento</option>{departments.map(d=><option key={d.code} value={d.code}>{d.label}</option>)}</select></td><td><select value={u.status} onChange={e=>updateLocal(u.id,{status:e.target.value as Status})}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></td><td><input placeholder="Motivo" value={u.status_reason||""} onChange={e=>updateLocal(u.id,{status_reason:e.target.value})}/>{u.status==='suspended'&&<input type="datetime-local" value={u.status_until ? new Date(u.status_until-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):""} onChange={e=>updateLocal(u.id,{status_until:e.target.value?new Date(e.target.value).getTime():null})}/>}</td><td>{u.last_login_at ? new Date(u.last_login_at).toLocaleString("pt-PT") : "Nunca"}</td><td><button className="row-action" onClick={()=>void saveUser(u)} title="Guardar utilizador"><UserCog size={17}/></button></td></tr>)}</tbody></table>{visible.length===0&&<p className="admin-empty">Nenhum utilizador corresponde aos filtros.</p>}</div>}</section></AppShell>;
}
