"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Building2, GraduationCap, LoaderCircle, MapPinned, Search } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { AppToast, ToastKind } from "@/components/app-toast";
import { AuthGuard } from "@/components/auth-guard";
import { ModuleGuard } from "@/components/module-guard";
import { useAuth } from "@/components/auth-context";
import { useI18n } from "@/components/i18n-context";
import { useModuleEnabled } from "@/components/use-module-enabled";
import styles from "./campus-directory.module.css";

type Room = { id: string; code: string; name: string; room_type: string; capacity: number | null; directions: string; accessibility_notes: string; building_name: string; building_code: string; level: string; floor_label: string };
type Faculty = { id: string; full_name: string; title: string; email: string | null; office: string | null; notes: string; units: Array<{ id: string; code: string; name: string }> };
type Building = { id: string; name: string; code: string; address: string; map_url: string | null; accessibility_notes: string };
type Notice = { kind: ToastKind; message: string } | null;

export function CampusDirectory() {
  const { t } = useI18n();
  const { user } = useAuth();
  const managementEnabled = useModuleEnabled("campus.management");
  const canManage = managementEnabled && (user?.role === "admin" || user?.commissionDepartment === "management");
  const [rooms, setRooms] = useState<Room[]>([]), [faculty, setFaculty] = useState<Faculty[]>([]), [buildings, setBuildings] = useState<Building[]>([]);
  const [query, setQuery] = useState(""), [tab, setTab] = useState<"rooms" | "faculty">("rooms"), [loading, setLoading] = useState(true), [notice, setNotice] = useState<Notice>(null), [editor, setEditor] = useState<"building" | "faculty" | null>(null), [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ name: "", code: "", email: "", title: "", address: "" });
  useEffect(() => {
    const preset = new URLSearchParams(window.location.search).get("q")?.trim();
    // The query is an external navigation input; copy it once after hydration.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    if (preset) setQuery(current => current || preset.slice(0, 100));
  }, []);
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch(`/api/campus?q=${encodeURIComponent(query)}`, { cache: "no-store" }); const data = await response.json() as { rooms?: Room[]; faculty?: Faculty[]; buildings?: Building[]; error?: string }; if (!response.ok) throw new Error(data.error || t("campus.loadError")); setRooms(data.rooms || []); setFaculty(data.faculty || []); setBuildings(data.buildings || []); } catch (error) { setNotice({ kind: "error", message: error instanceof Error ? error.message : t("campus.loadError") }); } finally { setLoading(false); } }, [query, t]);
  useEffect(() => { const timeout = window.setTimeout(() => void load(), 180); return () => window.clearTimeout(timeout); }, [load]);
  const save = async (event: FormEvent) => { event.preventDefault(); if (!editor) return; setSaving(true); try { const entity = editor; const response = await fetch("/api/campus", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ entity, name: form.name, code: form.code, email: form.email, title: form.title, address: form.address }) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error || t("campus.loadError")); setEditor(null); setForm({ name: "", code: "", email: "", title: "", address: "" }); setNotice({ kind: "success", message: t("campus.saved") }); await load(); } catch (error) { setNotice({ kind: "error", message: error instanceof Error ? error.message : t("campus.loadError") }); } finally { setSaving(false); } };
  const counts = useMemo(() => ({ rooms: rooms.length, faculty: faculty.length, buildings: buildings.length }), [buildings.length, faculty.length, rooms.length]);
  return <AuthGuard><ModuleGuard moduleKey="campus.directory"><AppShell active="campus" breadcrumb={t("campus.breadcrumb")}>{notice && <AppToast kind={notice.kind} message={notice.message} onDismiss={() => setNotice(null)} />}<section className={styles.heading}><div><span className="eyebrow">{t("campus.eyebrow")}</span><h1>{t("campus.title")}</h1><p>{t("campus.intro")}</p></div>{canManage && <div className={styles.actions}><button className="button button--secondary button--compact" type="button" onClick={() => setEditor("building")}><Building2 />{t("campus.newBuilding")}</button><button className="button button--primary button--compact" type="button" onClick={() => setEditor("faculty")}><GraduationCap />{t("campus.newFaculty")}</button></div>}</section>
    <section className={styles.panel}><div className={styles.toolbar}><label className={styles.search}><span className="sr-only">{t("campus.search")}</span><Search /><input value={query} onChange={event => setQuery(event.target.value)} placeholder={t("campus.searchPlaceholder")} /></label><div className={styles.tabs}><button type="button" className={tab === "rooms" ? styles.activeTab : ""} onClick={() => setTab("rooms")}>{t("campus.rooms")} <b>{counts.rooms}</b></button><button type="button" className={tab === "faculty" ? styles.activeTab : ""} onClick={() => setTab("faculty")}>{t("campus.faculty")} <b>{counts.faculty}</b></button></div></div>{loading ? <div className={styles.empty}><LoaderCircle className={styles.spin} />{t("community.common.loading")}</div> : tab === "rooms" ? rooms.length ? <div className={styles.list}>{rooms.map(room => <article className={styles.row} key={room.id}><span className={styles.rowIcon}><MapPinned /></span><div><strong>{room.code} · {room.name}</strong><p>{room.building_code} · {room.building_name} · {t("campus.floor", { level: room.level })}{room.capacity ? ` · ${t("campus.capacity", { capacity: room.capacity })}` : ""}</p>{room.directions && <small>{room.directions}</small>}</div></article>)}</div> : <div className={styles.empty}><MapPinned /><strong>{t("campus.noRooms")}</strong></div> : faculty.length ? <div className={styles.list}>{faculty.map(item => <article className={styles.row} key={item.id}><span className={styles.rowIcon}><GraduationCap /></span><div><strong>{item.full_name}</strong><p>{item.title}{item.office ? ` · ${t("campus.office")}: ${item.office}` : ""}</p>{item.email && <a href={`mailto:${item.email}`}>{item.email}</a>}{item.units.length > 0 && <small>{t("campus.units")}: {item.units.map(unit => unit.code).join(", ")}</small>}</div></article>)}</div> : <div className={styles.empty}><GraduationCap /><strong>{t("campus.noFaculty")}</strong></div>}</section>
    {editor && <div className={styles.dialog}><form onSubmit={save}><h2>{editor === "building" ? t("campus.newBuilding") : t("campus.newFaculty")}</h2><label>{t("campus.name")}<input required value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} /></label><label>{t("campus.code")}<input required value={form.code} onChange={event => setForm({ ...form, code: event.target.value })} /></label>{editor === "faculty" && <><label>{t("campus.email")}<input type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} /></label><label>{t("campus.title")}<input value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} /></label></>}{editor === "building" && <label>{t("campus.address")}<input value={form.address} onChange={event => setForm({ ...form, address: event.target.value })} /></label>}<footer><button className="button button--secondary" type="button" onClick={() => setEditor(null)}>{t("campus.cancel")}</button><button className="button button--primary" disabled={saving}>{saving && <LoaderCircle className={styles.spin} />}{t("campus.save")}</button></footer></form></div>}</AppShell></ModuleGuard></AuthGuard>;
}
