/* eslint-disable react-hooks/set-state-in-effect */
"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {ArrowRight,ChevronLeft,ChevronRight,ChevronsLeft,ChevronsRight,CircleAlert,ShieldCheck,UserRoundSearch} from "lucide-react";

export type PreflightIssue = {severity:"blocker"|"warning";code:string;message:string;classId?:number;studentId?:string;studentName?:string;studentNumber?:string};
export type PreflightCheck = {key:string;label:string;description:string;status:"passed"|"blocked"|"warning";count:number};
export type DistributionPreflightResult = {ready:boolean;checkedAt:number;summary:{classes:number;students:number;blockers:number;warnings:number;automaticStays:number;exceptionalPending:number};checks:PreflightCheck[];issues:PreflightIssue[];simulation?:{possible:boolean;moved:number;manualReviews:number;randomized?:number;tieBreaks?:number;tieBreakStudents?:number;classCounts:Record<string,number>;competition?:Array<{classId:number;candidates:number;placed:number;notPlaced:number;finalSize:number;maximumSize:number;originSize?:number;firstChoiceCandidates?:number;otherChoiceCandidates?:number;firstChoicePlaced?:number;candidateCapacity?:number}>}|null};

const groupLabels:Record<string,string>={TURMA_NAO_SUBMETIDA:"Turmas por submeter",TURMA_VAZIA:"Turmas sem estudantes",NUMERO_INVALIDO:"Números mecanográficos inválidos",PREFERENCIAS_EM_FALTA:"Preferências incompletas",DESTINO_INVALIDO:"Destinos inválidos",ORDEM_PREFERENCIAS_INVALIDA:"Ordem de preferências inválida",INFORMACAO_POR_VALIDAR:"Informação adicional por validar",INFORMACAO_VALIDADA_SEM_PONTOS:"Informação válida sem pontos extra",DESEQUILIBRIO:"Desequilíbrio atual entre turmas",DISTRIBUICAO_IMPOSSIVEL:"Pré-visualização sem solução",DISTRIBUICAO_ATIVA:"Distribuição já ativa"};

export function DistributionPreflight({result,onReviewStudent}:{result:DistributionPreflightResult;onReviewStudent:(studentId:string)=>void}){
 const [severity,setSeverity]=useState<"all"|"blocker"|"warning">("all"),[category,setCategory]=useState("all"),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(10);
 const categories=useMemo(()=>[...new Set(result.issues.map(issue=>issue.code))],[result.issues]);
 const filtered=useMemo(()=>result.issues.filter(issue=>(severity==="all"||issue.severity===severity)&&(category==="all"||issue.code===category)),[result.issues,severity,category]);
 const pages=Math.max(1,Math.ceil(filtered.length/pageSize)),currentPage=Math.min(page,pages),start=(currentPage-1)*pageSize,shown=filtered.slice(start,start+pageSize);
 const groups=Object.entries(shown.reduce<Record<string,PreflightIssue[]>>((all,issue)=>({...all,[issue.code]:[...(all[issue.code]||[]),issue]}),{}));
 const tieBreakCount=result.simulation?.tieBreakStudents??result.simulation?.tieBreaks??result.simulation?.randomized??0;
 const competition=(result.simulation?.competition||[]).map(item=>{const originSize=item.originSize??Math.max(0,item.finalSize-item.placed),firstChoice=item.firstChoiceCandidates??item.candidates,otherChoices=item.otherChoiceCandidates??Math.max(0,item.candidates-firstChoice),maximumVacancies=item.candidateCapacity??Math.max(0,item.maximumSize-originSize),firstChoiceCollisions=item.firstChoicePlaced==null?Math.max(0,item.notPlaced):Math.max(0,firstChoice-item.firstChoicePlaced);return {...item,originSize,firstChoice,otherChoices,maximumVacancies,firstChoiceCollisions}}).sort((a,b)=>b.firstChoiceCollisions-a.firstChoiceCollisions||b.firstChoice-a.firstChoice||a.classId-b.classId);
 const firstChoiceCollisions=competition.reduce((total,item)=>total+item.firstChoiceCollisions,0);
 useEffect(()=>{setPage(1)},[severity,category,pageSize]);
 useEffect(()=>{if(page>pages)setPage(pages)},[page,pages]);
 return <section className={`panel placement-preflight ${result.ready?"is-ready":"is-blocked"}`} aria-labelledby="preflight-title">
  <header className="placement-preflight__header"><span className="placement-preflight__status" aria-hidden="true">{result.ready?<ShieldCheck/>:<CircleAlert/>}</span><div><span className="eyebrow">Pré-validação operacional</span><h2 id="preflight-title">{result.ready?"Tudo pronto para calcular":"Resolve os bloqueadores antes de calcular"}</h2>{!result.ready&&<p>{result.summary.blockers} {result.summary.blockers===1?"bloqueador":"bloqueadores"} impedem a criação de uma proposta.</p>}</div><time dateTime={new Date(result.checkedAt).toISOString()}>Verificado em {new Date(result.checkedAt).toLocaleString("pt-PT")}</time></header>
  {result.simulation?.possible&&<div className="placement-preflight__simulation">
   <div className="placement-preflight__simulation-summary">
    <div><span className="eyebrow">Pré-visualização do cálculo</span><strong>Resultado previsto neste momento</strong>{result.simulation.manualReviews>0&&<small>{result.simulation.manualReviews} {result.simulation.manualReviews===1?"revisão manual prevista":"revisões manuais previstas"}</small>}</div>
    <div className="placement-preflight__simulation-kpis">
     <span><strong>{result.simulation.moved}</strong><small>Mudanças previstas</small></span>
     <span><strong>{result.summary.classes}</strong><small>Turmas analisadas</small></span>
     <span className={firstChoiceCollisions>0?"is-warning":""}><strong>{firstChoiceCollisions}</strong><small>Colisões na 1.ª opção</small></span>
     <span><strong>{tieBreakCount}</strong><small>Desempates decisivos</small></span>
    </div>
   </div>
   {competition.length?<div className="placement-preflight__competition">
    <div className="placement-preflight__competition-table-wrap"><table className="placement-preflight__competition-table" aria-label="Concorrência e lotação previstas por turma"><thead><tr><th>Turma</th><th title="Número atual de estudantes na turma">Atual</th><th title="Candidatos em primeira opção">1.ª opção</th><th title="Candidatos noutras posições">Outras</th><th title="Máximo de vagas disponíveis para candidatos, respeitando a diferença máxima de três estudantes entre turmas">Vagas máx.</th><th title="Colocações previstas">Previstas</th><th title="Pedidos de primeira opção não obtidos">Colisões 1.ª opção</th><th>Lotação</th></tr></thead><tbody>{competition.map(item=><tr key={item.classId} className={item.firstChoiceCollisions>0?"is-contested":""}><td><strong>Turma {item.classId}</strong></td><td>{item.originSize}</td><td>{item.firstChoice}</td><td>{item.otherChoices}</td><td>{item.maximumVacancies}</td><td>{item.placed}</td><td><span className={item.firstChoiceCollisions>0?"is-collision":""}>{item.firstChoiceCollisions}</span></td><td><strong>{item.finalSize}/{item.maximumSize}</strong></td></tr>)}</tbody></table></div>
    <p className="placement-preflight__competition-legend"><span><strong>Vagas máx.</strong> já respeita a diferença máxima de 3 estudantes entre turmas.</span><span><strong>Colisões</strong> são pedidos de 1.ª opção não obtidos.</span></p>
   </div>:<div className="placement-preflight__competition-fallback">{Object.entries(result.simulation.classCounts).map(([classId,count])=><span key={classId}>Turma {classId}<strong>{count}</strong></span>)}</div>}
  </div>}
  {result.issues.length>0&&<div className="preflight-results"><div className="preflight-results__toolbar"><div><strong>Casos a rever</strong><span>{filtered.length?`${start+1}–${Math.min(start+pageSize,filtered.length)} de ${filtered.length}`:"0 casos"}</span></div><label>Prioridade<select aria-label="Filtrar por prioridade" value={severity} onChange={event=>setSeverity(event.target.value as typeof severity)}><option value="all">Todas</option><option value="blocker">Bloqueadores</option><option value="warning">Avisos</option></select></label><label>Categoria<select aria-label="Filtrar por categoria" value={category} onChange={event=>setCategory(event.target.value)}><option value="all">Todas</option>{categories.map(code=><option key={code} value={code}>{groupLabels[code]||code.replaceAll("_"," ")}</option>)}</select></label><label>Por página<select aria-label="Casos por página" value={pageSize} onChange={event=>setPageSize(Number(event.target.value))}><option value="10">10</option><option value="25">25</option><option value="50">50</option></select></label></div>
   {groups.length>0?<div className="placement-preflight__issues">{groups.map(([code,issues])=><section key={code} className={`preflight-group is-${issues[0].severity}`}><header><div><strong>{groupLabels[code]||code.replaceAll("_"," ")}</strong><span>{issues.length} nesta página</span></div></header><div>{issues.map((issue,index)=><article key={`${issue.studentId||issue.classId||index}-${index}`}><div><strong>{issue.studentName||issue.message}</strong>{issue.studentNumber&&<span>{issue.studentNumber}</span>}<small>{issue.studentName?issue.message:issue.classId?`Turma ${issue.classId}`:issue.code}</small></div>{issue.studentId?<button type="button" onClick={()=>onReviewStudent(issue.studentId!)}><UserRoundSearch/>Rever aluno</button>:issue.classId?<Link href={`/turmas/${issue.classId}`}>Abrir Turma {issue.classId}<ArrowRight/></Link>:null}</article>)}</div></section>)}</div>:<div className="empty-state">Não existem casos com estes filtros.</div>}
   {filtered.length>0&&<nav className="placement-pagination" aria-label="Paginação dos casos da pré-validação"><span>Página <strong>{currentPage}</strong> de <strong>{pages}</strong></span><div><button type="button" aria-label="Primeira página de casos" disabled={currentPage===1} onClick={()=>setPage(1)}><ChevronsLeft/></button><button type="button" aria-label="Página anterior de casos" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}><ChevronLeft/></button><button type="button" aria-label="Página seguinte de casos" disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}><ChevronRight/></button><button type="button" aria-label="Última página de casos" disabled={currentPage===pages} onClick={()=>setPage(pages)}><ChevronsRight/></button></div></nav>}
  </div>}
 </section>
}
