/* eslint-disable react-hooks/set-state-in-effect */
"use client";

import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
import {AlertTriangle,CheckCircle2,Download,Grid3X3,RefreshCw,ShieldAlert} from "lucide-react";
import {AppShell} from "@/components/app-shell";
import {AuthGuard} from "@/components/auth-guard";

type Result={ready:boolean;checkedAt:number;summary:{classes:number;students:number;blockers:number;warnings:number;automaticStays:number;exceptionalPending:number;invalidReferences:number};issues:Array<{severity:"blocker"|"warning";code:string;message:string;classId?:number}>};

export function DistributionCheck(){
 const [result,setResult]=useState<Result|null>(null),[loading,setLoading]=useState(true),[notice,setNotice]=useState("");
 const run=useCallback(async()=>{setLoading(true);setNotice("");try{const response=await fetch("/api/admin/distribution-check",{cache:"no-store"}),data=await response.json() as Result&{error?:string};if(!response.ok)throw new Error(data.error||"Não foi possível verificar.");setResult(data)}catch(error){setNotice((error as Error).message)}finally{setLoading(false)}},[]);
 useEffect(()=>{void run()},[run]);
 return <AuthGuard requireAdmin><AppShell active="check" breadcrumb="Verificador"><section className="page-heading"><div><span className="eyebrow">Preparação dos dados</span><h1>Verificador</h1><p>Confirma todas as garantias antes de o Núcleo calcular as colocações.</p></div><button className="button button--secondary" onClick={()=>void run()} disabled={loading}><RefreshCw className={loading?"spin":""}/>Verificar novamente</button></section>{notice&&<p className="admin-notice">{notice}</p>}{result&&<><section className={`verification-hero ${result.ready?"is-ready":"is-blocked"}`}>{result.ready?<CheckCircle2/>:<ShieldAlert/>}<div><strong>{result.ready?"Dados prontos para calcular":"Ainda existem bloqueadores"}</strong><span>{result.summary.blockers} bloqueadores · {result.summary.warnings} avisos · {result.summary.students} estudantes</span></div></section><section className="placement-kpis verifier-kpis"><article><strong>{result.summary.automaticStays}</strong><span>Sem formulário · ficam automaticamente</span></article><article><strong>{result.summary.exceptionalPending}</strong><span>Exceções por avaliar</span></article><article><strong>{result.summary.invalidReferences}</strong><span>Referências sem ponto</span></article><article><strong>{result.summary.classes}</strong><span>Turmas verificadas</span></article></section><section className="panel distribution-export"><div className="distribution-export__copy"><span className="eyebrow">Garantia de permanência</span><h2>Quem não submeteu fica na turma atual</h2><p>A ausência de formulário nunca deixa um estudante sem colocação nem o coloca automaticamente noutra turma.</p></div><div><a className="button button--secondary" href="/api/admin/export-validation" download><Download/>Exportar Excel</a><Link className="button button--primary" href="/admin/colocacoes"><Grid3X3/>Abrir Colocações</Link></div></section><section className="panel"><div className="panel__header"><div><h2>Validações</h2><p>Última execução: {new Date(result.checkedAt).toLocaleString("pt-PT")}</p></div></div><div className="verification-list">{result.issues.map((issue,index)=><article key={`${issue.code}-${index}`} className={`verification-issue ${issue.severity}`}><AlertTriangle/><div><strong>{issue.message}</strong><small>{issue.code}{issue.classId?` · Turma ${issue.classId}`:""}</small></div></article>)}{!result.issues.length&&<div className="empty-state">Todas as validações foram concluídas sem problemas.</div>}</div></section></>}</AppShell></AuthGuard>;
}
