"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Download, FileArchive, FileText, Filter, LoaderCircle, LockKeyhole, Plus, Trash2, Users } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { AppToast, ToastKind } from "@/components/app-toast";
import { AuthGuard } from "@/components/auth-guard";
import { useAuth } from "@/components/auth-context";
import { ModuleGuard } from "@/components/module-guard";
import { useModuleEnabled } from "@/components/use-module-enabled";
import styles from "@/components/documents-library.module.css";

type DateInput = string | number;
type DocumentItem = { id: string; title: string; description: string; type: string; visibility: string; fileName: string; fileUrl: string; unitId: string; unitName: string; authorName: string; createdAt: DateInput };
type Unit = { id: string; code: string; name: string };
type Notice = { kind: ToastKind; message: string } | null;
const typeLabels: Record<string, string> = { document: "Documento", minutes: "Ata", regulation: "Regulamento", form: "Formulário" };
const visibilityLabels: Record<string, string> = { authenticated: "Estudantes autenticados", commission: "Comissão de Curso", public: "Público" };
function first(raw: Record<string, unknown>, ...keys: string[]) { for (const key of keys) if (raw[key] != null) return raw[key]; return undefined; }
function dateInput(raw: unknown): DateInput { return typeof raw === "number" ? raw : String(raw || new Date().toISOString()); }
function formatCreatedAt(value: DateInput) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "Data por confirmar" : new Intl.DateTimeFormat("pt-PT", { dateStyle: "medium" }).format(date); }
function normalise(raw: Record<string, unknown>): DocumentItem { const unit = (raw.unit && typeof raw.unit === "object" ? raw.unit : {}) as Record<string, unknown>; return { id: String(raw.id), title: String(raw.title || "Documento"), description: String(raw.description || ""), type: String(first(raw, "type", "documentType", "document_type") || "document"), visibility: String(raw.visibility || "authenticated"), fileName: String(first(raw, "fileName", "file_name", "attachmentName", "attachment_name") || "documento"), fileUrl: String(first(raw, "fileUrl", "file_url", "url", "attachmentDataUrl", "attachment_data_url") || ""), unitId: String(first(raw, "unitId", "unit_id") ?? unit.id ?? ""), unitName: String(first(raw, "unitName", "unit_name") ?? unit.name ?? ""), authorName: String(first(raw, "authorName", "author_name") || "Comissão de Curso"), createdAt: dateInput(first(raw, "createdAt", "created_at")) }; }

export function DocumentsLibrary() {
  const { user } = useAuth(); const managementEnabled = useModuleEnabled("documents.management"); const canManage = managementEnabled && (user?.role === "admin" || Boolean(user?.commissionPosition));
  const [documents, setDocuments] = useState<DocumentItem[]>([]); const [units, setUnits] = useState<Unit[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [editor, setEditor] = useState(false);
  const [typeFilter, setTypeFilter] = useState("all"); const [unitFilter, setUnitFilter] = useState("all"); const [notice, setNotice] = useState<Notice>(null);
  const [form, setForm] = useState({ title: "", description: "", type: "document", visibility: "authenticated", unitId: "" }); const [file, setFile] = useState<File | null>(null);
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/documents", { cache: "no-store" }); const data = await response.json() as { documents?: Record<string, unknown>[]; units?: Record<string, unknown>[]; curricularUnits?: Record<string, unknown>[]; error?: string }; if (!response.ok) throw new Error(data.error || "Não foi possível carregar os documentos."); setDocuments((data.documents || []).map(normalise)); setUnits((data.units || data.curricularUnits || []).map(raw => ({ id: String(raw.id), code: String(raw.code || ""), name: String(raw.name || "") }))); } catch (error) { setNotice({ kind: "error", message: error instanceof Error ? error.message : "Não foi possível carregar os documentos." }); } finally { setLoading(false); } }, []);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => documents.filter(item => (typeFilter === "all" || item.type === typeFilter) && (unitFilter === "all" || item.unitId === unitFilter)).sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()), [documents, typeFilter, unitFilter]);
  const save = async (event: FormEvent) => { event.preventDefault(); if (!file) { setNotice({ kind: "warning", message: "Seleciona o ficheiro que pretendes publicar." }); return; } if (file.size > 4 * 1024 * 1024) { setNotice({ kind: "warning", message: "O ficheiro não pode ultrapassar 4 MB." }); return; } setSaving(true); try { const payload = new FormData(); Object.entries(form).forEach(([key, val]) => payload.set(key, val)); payload.set("file", file); const response = await fetch("/api/documents", { method: "POST", body: payload }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error || "Não foi possível publicar o documento."); setForm({ title: "", description: "", type: "document", visibility: "authenticated", unitId: "" }); setFile(null); setEditor(false); setNotice({ kind: "success", message: "Documento publicado." }); await load(); } catch (error) { setNotice({ kind: "error", message: error instanceof Error ? error.message : "Não foi possível publicar o documento." }); } finally { setSaving(false); } };
  const remove = async (id: string) => { if (!window.confirm("Eliminar este documento?")) return; try { const response = await fetch("/api/documents", { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ id }) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error || "Não foi possível eliminar o documento."); setNotice({ kind: "success", message: "Documento eliminado." }); await load(); } catch (error) { setNotice({ kind: "error", message: error instanceof Error ? error.message : "Não foi possível eliminar o documento." }); } };
  return <AuthGuard><ModuleGuard moduleKey="documents.library"><AppShell active="documents" breadcrumb="Documentos e atas">
    {notice && <AppToast kind={notice.kind} message={notice.message} onDismiss={() => setNotice(null)} />}
    <section className={styles.hero}><div className={styles.heroIcon}><FileArchive /></div><div><span className="eyebrow">Arquivo da Comissão de Curso</span><h1>Documentos e atas</h1><p>Consulta atas, regulamentos, formulários e outros documentos úteis.</p></div>{canManage && <button className="button button--primary" onClick={() => setEditor(v => !v)}><Plus />{editor ? "Fechar" : "Publicar documento"}</button>}</section>
    {canManage && editor && <form className={`${styles.panel} ${styles.form}`} onSubmit={save}><div className={styles.formHeading}><h2>Novo documento</h2><p>Define claramente quem poderá consultar o ficheiro.</p></div><div className={styles.formGrid}>
      <label className={styles.wide}><span>Título</span><input required maxLength={180} value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></label>
      <label><span>Tipo</span><select value={form.type} onChange={e => setForm({ ...form, type: e.target.value })}>{Object.entries(typeLabels).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label>
      <label><span>Visibilidade</span><select value={form.visibility} onChange={e => setForm({ ...form, visibility: e.target.value })}><option value="authenticated">Estudantes autenticados</option><option value="commission">Apenas Comissão de Curso</option><option value="public">Público</option></select></label>
      <label className={styles.wide}><span>Unidade curricular <small>(opcional)</small></span><select value={form.unitId} onChange={e => setForm({ ...form, unitId: e.target.value })}><option value="">Documento geral</option>{units.map(unit => <option key={unit.id} value={unit.id}>{unit.code} · {unit.name}</option>)}</select></label>
      <label className={styles.full}><span>Descrição <small>(opcional)</small></span><textarea rows={3} maxLength={1500} value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></label>
      <label className={`${styles.full} ${styles.fileField}`}><span>Ficheiro</span><input required type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.odt,.ods,.txt,image/*" onChange={e => setFile(e.target.files?.[0] || null)} /><small>PDF, imagem, documento Office ou formato aberto, até 4 MB. Não incluas dados pessoais desnecessários.</small></label>
    </div><footer className={styles.formActions}><button className="button button--primary" disabled={saving}>{saving && <LoaderCircle className={styles.spin} />}{saving ? "A publicar…" : "Publicar documento"}</button></footer></form>}
    <section className={styles.panel}><div className={styles.filterBar}><span><Filter />Filtrar arquivo</span><label><span className={styles.srOnly}>Tipo</span><select value={typeFilter} onChange={e => setTypeFilter(e.target.value)}><option value="all">Todos os tipos</option>{Object.entries(typeLabels).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label><label><span className={styles.srOnly}>Unidade curricular</span><select value={unitFilter} onChange={e => setUnitFilter(e.target.value)}><option value="all">Todas as unidades curriculares</option>{units.map(unit => <option key={unit.id} value={unit.id}>{unit.code} · {unit.name}</option>)}</select></label></div>
      {loading ? <div className={styles.loading}><LoaderCircle className={styles.spin} />A carregar arquivo…</div> : visible.length === 0 ? <div className={styles.empty}><FileText /><strong>Ainda não existem documentos</strong><span>Os documentos publicados aparecerão aqui.</span></div> : <div className={styles.cardGrid}>{visible.map(item => <article className={styles.fileCard} key={item.id}><div className={styles.fileIcon}>{item.type === "minutes" ? <FileArchive /> : <FileText />}</div><div><div className={styles.badgeRow}><span className={styles.badge}>{typeLabels[item.type] || item.type}</span><span className={styles.softBadge}>{item.visibility === "commission" ? <LockKeyhole /> : <Users />}{visibilityLabels[item.visibility] || item.visibility}</span></div><h2>{item.title}</h2>{item.description && <p>{item.description}</p>}<small>{item.unitName || "Arquivo geral"} · {item.authorName} · {formatCreatedAt(item.createdAt)}</small></div><div className={styles.cardActions}>{item.fileUrl && <a className="button" href={item.fileUrl} download={item.fileName}><Download />Descarregar</a>}{canManage && <button className={styles.iconDanger} onClick={() => void remove(item.id)} aria-label={`Eliminar ${item.title}`}><Trash2 /></button>}</div></article>)}</div>}
    </section>
  </AppShell></ModuleGuard></AuthGuard>;
}
