"use client";

import Link from "next/link";
import { Archive, ArchiveRestore, Bell, BellRing, BookOpen, CalendarDays, Check, CheckCheck, ChevronRight, Clock3, Inbox, LoaderCircle, Megaphone, RefreshCw, Save, Settings2, Vote } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { AppToast, ToastKind } from "@/components/app-toast";
import { useI18n } from "@/components/i18n-context";
import styles from "@/components/notifications-center.module.css";

type Notification = { id: string; sourceType: string; sourceId: string; title: string; body: string; category: string; priority: string; unitId: string; unitName: string; createdAt: string | null; read: boolean; archived: boolean; href: string };
type Preferences = { categories: Record<string, boolean>; urgentOnly: boolean; unitIds: string[]; email: boolean };
type Unit = { id: string; name: string; code: string };
type Notice = { kind: ToastKind; message: string } | null;
const categories = ["announcements", "calendar", "materials", "polls", "requests"] as const;
const categoryTranslationKeys = { announcements: "notifications.categories.announcements", calendar: "notifications.categories.calendar", materials: "notifications.categories.materials", polls: "notifications.categories.polls", requests: "notifications.categories.requests" } as const;
const obj = (value: unknown): Record<string, unknown> => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
const str = (item: Record<string, unknown>, ...keys: string[]) => { for (const key of keys) if (typeof item[key] === "string" && item[key]) return String(item[key]); return ""; };
const bool = (item: Record<string, unknown>, ...keys: string[]) => { for (const key of keys) if (typeof item[key] === "boolean") return item[key] as boolean; return false; };
const cat = (value: string) => ({ announcement: "announcements", announcements: "announcements", event: "calendar", calendar_event: "calendar", material: "materials", poll: "polls", survey: "polls", request: "requests", ticket: "requests" }[value] || value || "announcements");
function normaliseNotification(raw: unknown, index: number): Notification { const item = obj(raw), sourceType = str(item, "sourceType", "type"), sourceId = str(item, "sourceId") || str(item, "id", "notificationId") || String(index), category = cat(str(item, "category") || sourceType); return { id: str(item, "id", "notificationId") || `${sourceType}:${sourceId}`, sourceType, sourceId, title: str(item, "title", "subject"), body: str(item, "body", "message", "description", "excerpt"), category, priority: str(item, "priority"), unitId: str(item, "unitId", "curricularUnitId"), unitName: str(item, "unitName", "curricularUnitName", "unitCode"), createdAt: str(item, "createdAt", "occurredAt", "publishedAt", "timestamp") || null, read: bool(item, "read", "isRead") || Boolean(item.readAt), archived: bool(item, "archived", "isArchived") || Boolean(item.archivedAt), href: str(item, "href", "url") || ({ announcements: "/avisos", calendar: "/calendario", materials: "/materiais", polls: "/inqueritos", requests: "/pedidos" }[category] || "/") }; }
function normalisePreferences(payload: unknown) { const root = obj(payload), source = obj(root.preferences || root), categorySource = obj(source.categories), enabled = Array.isArray(source.enabledCategories) ? source.enabledCategories.map(String) : null; const prefs: Preferences = { categories: Object.fromEntries(categories.map(key => [key, enabled ? enabled.includes(key) : typeof source[key] === "boolean" ? source[key] : categorySource[key] !== false])), urgentOnly: bool(source, "urgentOnly", "onlyUrgent"), unitIds: (Array.isArray(source.unitIds) ? source.unitIds : Array.isArray(source.curricularUnitIds) ? source.curricularUnitIds : []).map(String), email: bool(source, "email") }; const rawUnits = (Array.isArray(root.units) ? root.units : Array.isArray(root.curricularUnits) ? root.curricularUnits : []) as unknown[]; return { prefs, units: rawUnits.map(raw => { const item = obj(raw); return { id: str(item, "id"), name: str(item, "name"), code: str(item, "code", "acronym") }; }).filter(item => item.id) }; }

export function NotificationsCenter() {
  const { locale, t } = useI18n(); const [items, setItems] = useState<Notification[]>([]), [preferences, setPreferences] = useState<Preferences>({ categories: Object.fromEntries(categories.map(key => [key, true])), urgentOnly: false, unitIds: [], email: false }), [units, setUnits] = useState<Unit[]>([]), [tab, setTab] = useState<"all" | "unread" | "archived">("all"), [category, setCategory] = useState("all"), [loading, setLoading] = useState(true), [error, setError] = useState(""), [busy, setBusy] = useState(""), [saving, setSaving] = useState(false), [saved, setSaved] = useState(false), [notice, setNotice] = useState<Notice>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [feedResponse, prefResponse] = await Promise.all([fetch("/api/notifications?limit=100&includeArchived=true", { cache: "no-store" }), fetch("/api/notification-preferences", { cache: "no-store" })]), feedPayload = await feedResponse.json().catch(() => ({})) as unknown, prefPayload = await prefResponse.json().catch(() => ({})) as unknown; if (!feedResponse.ok) throw new Error(str(obj(feedPayload), "error", "message") || t("notifications.loadError")); const root = obj(feedPayload), raw = (Array.isArray(root.notifications) ? root.notifications : Array.isArray(root.items) ? root.items : Array.isArray(feedPayload) ? feedPayload : []) as unknown[]; setItems(raw.map(normaliseNotification)); if (prefResponse.ok) { const next = normalisePreferences(prefPayload); setPreferences(next.prefs); setUnits(next.units); } } catch (cause) { setError(cause instanceof Error ? cause.message : t("notifications.loadError")); } finally { setLoading(false); } }, [t]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  const unread = items.filter(item => !item.read && !item.archived).length;
  const priorityLabel = (value: string) => {
    const normalized = value.trim().toLocaleLowerCase("en");
    if (normalized === "urgent") return t("notifications.priority.urgent");
    if (normalized === "important") return t("notifications.priority.important");
    if (normalized === "normal") return t("notifications.priority.normal");
    return value;
  };
  const visible = useMemo(() => items.filter(item => (tab === "archived" ? item.archived : !item.archived) && (tab !== "unread" || !item.read) && (category === "all" || item.category === category)), [category, items, tab]);
  const patch = async (updates: Array<Record<string, unknown>>, key: string, optimistic: (item: Notification) => Notification) => { setBusy(key); const previous = items; setItems(current => current.map(optimistic)); try { const response = await fetch("/api/notifications", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(updates.length === 1 ? updates[0] : { items: updates }) }); const payload = await response.json().catch(() => ({})) as unknown; if (!response.ok) throw new Error(str(obj(payload), "error", "message") || t("notifications.actionError")); window.dispatchEvent(new CustomEvent("notifications:changed")); } catch (cause) { setItems(previous); setNotice({ kind: "error", message: cause instanceof Error ? cause.message : t("notifications.actionError") }); } finally { setBusy(""); } };
  const markRead = (item: Notification) => patch([{ sourceType: item.sourceType, sourceId: item.sourceId, read: true }], item.id, current => current.id === item.id ? { ...current, read: true } : current);
  const markAll = () => { const targets = items.filter(item => !item.read && !item.archived); return targets.length ? patch(targets.map(item => ({ sourceType: item.sourceType, sourceId: item.sourceId, read: true })), "all", item => item.archived ? item : { ...item, read: true }) : Promise.resolve(); };
  const setArchived = (item: Notification, archived: boolean) => patch([{ sourceType: item.sourceType, sourceId: item.sourceId, archived }], item.id, current => current.id === item.id ? { ...current, archived } : current);
  const savePreferences = async () => { setSaving(true); setSaved(false); try { const response = await fetch("/api/notification-preferences", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ announcements: preferences.categories.announcements, calendar: preferences.categories.calendar, polls: preferences.categories.polls, requests: preferences.categories.requests, materials: preferences.categories.materials, email: preferences.email, urgentOnly: preferences.urgentOnly, unitIds: preferences.unitIds }) }); const payload = await response.json().catch(() => ({})) as unknown; if (!response.ok) throw new Error(str(obj(payload), "error", "message") || t("notifications.preferences.error")); setSaved(true); window.setTimeout(() => setSaved(false), 2500); } catch (cause) { setNotice({ kind: "error", message: cause instanceof Error ? cause.message : t("notifications.preferences.error") }); } finally { setSaving(false); } };
  const Icon = ({ category: value }: { category: string }) => { const Component = value === "calendar" ? CalendarDays : value === "materials" ? BookOpen : value === "polls" ? Vote : value === "requests" ? Inbox : Megaphone; return <Component />; };
  return <AppShell active="notifications" breadcrumb="Notificações"><div className={styles.center}>{notice && <AppToast kind={notice.kind} message={notice.message} onDismiss={() => setNotice(null)} />}
    <header className={styles.heading}><div className={styles.headingCopy}><span className={styles.headingIcon}><BellRing /></span><div><span className="eyebrow">{t("notifications.eyebrow")}</span><h1>{t("notifications.title")}</h1><p>{t("notifications.description")}</p></div></div><div className={styles.headingActions}><button className="button button--secondary" type="button" disabled={!unread || Boolean(busy)} onClick={() => void markAll()}><CheckCheck />{t("notifications.markAll")}</button></div></header>
    <div className={styles.layout}><section className={styles.panel}><div className={styles.toolbar}><div className={styles.tabs} role="tablist" aria-label={t("notifications.filterState")}><button type="button" role="tab" aria-selected={tab === "all"} onClick={() => setTab("all")}>{t("notifications.tabs.all")}</button><button type="button" role="tab" aria-selected={tab === "unread"} onClick={() => setTab("unread")}>{t("notifications.tabs.unread")}<small>{unread}</small></button><button type="button" role="tab" aria-selected={tab === "archived"} onClick={() => setTab("archived")}>{t("notifications.tabs.archived")}</button></div><select className={styles.filter} value={category} onChange={event => setCategory(event.target.value)} aria-label={t("notifications.filterCategory")}><option value="all">{t("notifications.categories.all")}</option>{categories.map(key => <option value={key} key={key}>{t(categoryTranslationKeys[key])}</option>)}</select></div>
      {loading ? <div className={styles.state} aria-live="polite"><LoaderCircle className={styles.spinner} /><strong>{t("notifications.loading")}</strong></div> : error ? <div className={styles.state} role="alert"><Bell /><strong>{t("notifications.loadError")}</strong><span>{error}</span><button className={styles.retry} onClick={() => void load()} type="button"><RefreshCw size={13} /> {t("notifications.retry")}</button></div> : visible.length ? <div className={styles.list}>{visible.map(item => <article className={styles.notification} data-unread={!item.read} key={item.id}><span className={styles.icon} data-category={item.category}><Icon category={item.category} /></span><div className={styles.copy}><header><h2>{item.title || t("notifications.untitled")}</h2>{!item.read && <i className={styles.unreadDot} aria-label={t("notifications.unread")} />}{item.priority && <span className={styles.badge}>{priorityLabel(item.priority)}</span>}</header>{item.body && <p>{item.body}</p>}<div className={styles.meta}>{item.createdAt && <span><Clock3 />{new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.createdAt))}</span>}{item.unitName && <span><BookOpen />{item.unitName}</span>}</div></div><div className={styles.actions}>{!item.read && <button type="button" disabled={busy === item.id} onClick={() => void markRead(item)} aria-label={t("notifications.markRead")} title={t("notifications.markRead")}><Check /></button>}<button type="button" disabled={busy === item.id} onClick={() => void setArchived(item, !item.archived)} aria-label={t(item.archived ? "notifications.restore" : "notifications.archive")} title={t(item.archived ? "notifications.restore" : "notifications.archive")}>{item.archived ? <ArchiveRestore /> : <Archive />}</button><Link href={item.href} onClick={() => { if (!item.read) void markRead(item); }} aria-label={t("notifications.open")} title={t("notifications.open")}><ChevronRight /></Link></div></article>)}</div> : <div className={styles.state}><Bell /><strong>{tab === "unread" ? t("notifications.emptyUnread") : tab === "archived" ? t("notifications.emptyArchived") : t("notifications.empty")}</strong><span>{t("notifications.emptyHelp")}</span></div>}
    </section><aside className={`${styles.panel} ${styles.preferences}`}><header><span><Settings2 /></span><div><h2>{t("notifications.preferences.title")}</h2><p>{t("notifications.preferences.description")}</p></div></header><form onSubmit={event => { event.preventDefault(); void savePreferences(); }}><div className={styles.group}><strong>{t("notifications.preferences.categories")}</strong>{categories.map(key => <label className={styles.check} key={key}><input type="checkbox" checked={preferences.categories[key] !== false} onChange={event => setPreferences(current => ({ ...current, categories: { ...current.categories, [key]: event.target.checked } }))} /><span>{t(categoryTranslationKeys[key])}</span></label>)}</div><div className={styles.group}><strong>{t("notifications.preferences.priority")}</strong><label className={styles.check}><input type="checkbox" checked={preferences.urgentOnly} onChange={event => setPreferences(current => ({ ...current, urgentOnly: event.target.checked }))} /><span>{t("notifications.preferences.urgentOnly")}<small>{t("notifications.preferences.urgentHelp")}</small></span></label></div>{units.length > 0 && <div className={styles.group}><strong>{t("notifications.preferences.units")}</strong><select className={styles.unitSelect} multiple value={preferences.unitIds} onChange={event => setPreferences(current => ({ ...current, unitIds: Array.from(event.target.selectedOptions, option => option.value) }))}>{units.map(unit => <option value={unit.id} key={unit.id}>{unit.code ? `${unit.code} · ` : ""}{unit.name}</option>)}</select><p className={styles.help}>{t("notifications.preferences.unitsHelp")}</p></div>}<button className={styles.save} type="submit" disabled={saving}><Save />{saving ? t("notifications.preferences.saving") : t("notifications.preferences.save")}</button>{saved && <span className={styles.saved}><Check />{t("notifications.preferences.saved")}</span>}</form></aside></div>
  </div></AppShell>;
}
