/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {CheckCircle2,Filter,RefreshCw,Save,Search,ShieldAlert,X} from "lucide-react";
import {AppShell} from "@/components/app-shell";
import {AuthGuard} from "@/components/auth-guard";

type ValidationType=""|"friends_other_class"|"integration_bullying"|"other";
type Student={id:string;full_name:string;student_number:string;class_id:number;student_decision:"stay"|"move"|null;preference_source:"student"|"admin"|"automatic";preference_admin_reason:string|null;notes:string|null;considerations:string;exception_points:number;exception_reviewed_at:number|null;exception_review_reason:string|null;additional_info_validation:ValidationType|null;additional_info_validation_note:string|null;distribution_result:string|null};
type Destination={student_id:string;destination_class:number;rank:number};
type Move={studentId:string;originClass:number;destinationClass:number;rank:number|null;status:string;points?:number;manualReview:boolean;manualOverride?:boolean};
type Proposal={id:string;status:string;invalidated_at?:number;result_snapshot:string;created_at:number};
const validationLabels:Record<Exclude<ValidationType,"">,string>={friends_other_class:"Tem amigos noutra turma",integration_bullying:"Sofre bullying / está mal integrado",other:"Outro"};
function parseMoves(value?:string){try{const parsed=JSON.parse(value||"[]");return Array.isArray(parsed)?parsed as Move[]:[]}catch{return []}}

export function PlacementWorkbench(){
 const [students,setStudents]=useState<Student[]>([]),[destinations,setDestinations]=useState<Destination[]>([]),[proposals,setProposals]=useState<Proposal[]>([]),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[selectedId,setSelectedId]=useState<string|null>(null),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[action,setAction]=useState("");
 const load=useCallback(async()=>{setLoading(true);const [workbench,history]=await Promise.all([fetch("/api/admin/placements",{cache:"no-store"}),fetch("/api/admin/distribution-proposals",{cache:"no-store"})]);const data=await workbench.json() as {students?:Student[];destinations?:Destination[];error?:string},proposalData=await history.json() as {proposals?:Proposal[]};if(workbench.ok){setStudents(data.students||[]);setDestinations(data.destinations||[]);setProposals(proposalData.proposals||[])}else setNotice(data.error||"Não foi possível carregar as colocações.");setLoading(false)},[]);
 useEffect(()=>{void load()},[load]);
 const latest=proposals[0],moves=parseMoves(latest?.result_snapshot),moveById=useMemo(()=>new Map(moves.map(move=>[move.studentId,move])),[moves]);
 const visible=students.filter(student=>{const move=moveById.get(student.id),matches=`${student.full_name} ${student.student_number} ${student.class_id}`.toLowerCase().includes(query.toLowerCase());if(!matches)return false;if(filter==="automatic")return !student.student_decision;if(filter==="review")return Boolean(student.notes&&!student.exception_reviewed_at)||Boolean(move?.manualReview);if(filter==="moved")return move?.status==="moved";return true});
 const selected=students.find(student=>student.id===selectedId)||null;
 const act=async(kind:string)=>{setAction(kind);setNotice("");const response=await fetch(`/api/admin/distribution-proposals/${kind}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:latest?.id})}),data=await response.json() as {error?:string};setAction("");setNotice(response.ok?"Operação concluída e registada.":data.error||"Não foi possível concluir.");if(response.ok)await load()};
 return <AuthGuard requireAdmin><AppShell active="placements" breadcrumb="Colocações"><section className="page-heading placement-heading"><div><span className="eyebrow">Mesa de trabalho do Núcleo</span><h1>Colocações</h1><p>Valida informação adicional, revê preferências e prepara a melhor solução global.</p></div><button className="button button--secondary" onClick={()=>void load()} disabled={loading}><RefreshCw className={loading?"spin":""}/>Atualizar</button></section>{notice&&<p className="admin-notice" role="status">{notice}</p>}
 <section className="placement-kpis"><article><strong>{students.length}</strong><span>Estudantes</span></article><article><strong>{students.filter(student=>!student.student_decision).length}</strong><span>Permanências automáticas</span></article><article><strong>{students.filter(student=>student.student_decision==="move").length}</strong><span>Pretendem mudar</span></article><article><strong>{students.filter(student=>student.notes&&!student.exception_reviewed_at).length}</strong><span>Informações por validar</span></article><article><strong>{moves.filter(move=>move.status==="moved").length}</strong><span>Mudanças propostas</span></article></section>
 <section className="panel placement-runbar"><div><span className="eyebrow">Proposta</span><h2>{latest?`${latest.status}${latest.invalidated_at?" · invalidada":""}`:"Ainda não calculada"}</h2><p>O cálculo procura a melhor solução geral; resultados equivalentes são desempatedos por sorteio auditável.</p></div><div><button className="button button--secondary" disabled={Boolean(action)} onClick={()=>void act("calculate")}>Calcular nova proposta</button>{latest?.status==="draft"&&!latest.invalidated_at&&<button className="button button--primary" disabled={Boolean(action)} onClick={()=>void act("approve")}>Aprovar</button>}{latest?.status==="approved"&&<button className="button button--primary" disabled={Boolean(action)} onClick={()=>void act("apply")}>Aplicar</button>}{latest?.status==="applied"&&<><button className="button button--primary" disabled={Boolean(action)} onClick={()=>void act("publish")}>Publicar</button><button className="button button--secondary button--danger" disabled={Boolean(action)} onClick={()=>void act("rollback")}>Reverter</button></>}</div></section>
 <section className="panel placement-sheet"><div className="placement-toolbar"><label className="search-field"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Pesquisar nome, número ou turma"/></label><label><Filter size={15}/><select value={filter} onChange={event=>setFilter(event.target.value)}><option value="all">Todos</option><option value="automatic">Sem formulário</option><option value="review">Revisão necessária</option><option value="moved">Com mudança</option></select></label><span>{visible.length} linhas</span></div><div className="placement-table-wrap"><table><thead><tr><th>Estado</th><th>Estudante</th><th>Origem</th><th>Preferências</th><th>Validação CC</th><th>Destino proposto</th><th>Resultado</th></tr></thead><tbody>{visible.map(student=>{const own=destinations.filter(item=>item.student_id===student.id).sort((a,b)=>a.rank-b.rank),move=moveById.get(student.id),needs=Boolean(student.notes&&!student.exception_reviewed_at)||Boolean(move?.manualReview),validation=student.additional_info_validation?validationLabels[student.additional_info_validation]:student.notes?"Por validar":"Sem informação";return <tr key={student.id} className={needs?"needs-review":move?.status==="moved"?"is-moved":!student.student_decision?"is-automatic":""} onClick={()=>setSelectedId(student.id)}><td>{needs?<ShieldAlert/>:<CheckCircle2/>}</td><td><strong>{student.full_name}</strong><small>{student.student_number}</small></td><td>Turma {student.class_id}</td><td>{own.length?own.map(item=>`T${item.destination_class}`).join(" → "):!student.student_decision?"Automática · fica":"Ficar"}</td><td>{validation}</td><td>{move?`Turma ${move.destinationClass}`:"—"}</td><td>{move?.manualOverride?"Manual":move?.rank?`${move.rank}.ª preferência`:move?.status==="fallback"?"Mantém origem":move?.status==="stayed_by_choice"?"Fica":"Por calcular"}</td></tr>})}</tbody></table></div></section>
 {selected&&<PlacementEditor student={selected} destinations={destinations.filter(item=>item.student_id===selected.id).sort((a,b)=>a.rank-b.rank)} move={moveById.get(selected.id)} proposal={latest} onClose={()=>setSelectedId(null)} onSaved={async message=>{setNotice(message);setSelectedId(null);await load()}}/>}</AppShell></AuthGuard>
}

function PlacementEditor({student,destinations,move,proposal,onClose,onSaved}:{student:Student;destinations:Destination[];move?:Move;proposal?:Proposal;onClose:()=>void;onSaved:(message:string)=>Promise<void>}){
 const [destinationText,setDestinationText]=useState(destinations.map(item=>item.destination_class).join(", ")),[validationType,setValidationType]=useState<ValidationType>(student.additional_info_validation||""),[validationNote,setValidationNote]=useState(student.additional_info_validation_note||""),[reason,setReason]=useState(student.preference_admin_reason||""),[manualDestination,setManualDestination]=useState(move?.destinationClass||student.class_id),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const save=async()=>{setSaving(true);setError("");const parsed=destinationText.split(/[,; ]+/).filter(Boolean).map(Number),response=await fetch("/api/admin/placements",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({studentId:student.id,destinations:parsed,validationType,validationNote,reason})}),data=await response.json() as {error?:string};setSaving(false);if(!response.ok)return setError(data.error||"Não foi possível guardar.");await onSaved("Preferências e validação guardadas; a proposta anterior foi invalidada.")};
 const override=async()=>{if(!proposal)return;setSaving(true);const response=await fetch("/api/admin/distribution-proposals/override",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:proposal.id,studentId:student.id,destinationClass:manualDestination,reason})}),data=await response.json() as {error?:string};setSaving(false);if(!response.ok)return setError(data.error||"Não foi possível alterar.");await onSaved("Colocação manual guardada e auditada.")};
 return <div className="placement-drawer-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)onClose()}}><aside className="placement-drawer" role="dialog" aria-modal="true"><header><div><span className="eyebrow">Editor administrativo</span><h2>{student.full_name}</h2><p>{student.student_number} · Turma {student.class_id}</p></div><button onClick={onClose} aria-label="Fechar"><X/></button></header>{error&&<p className="admin-notice">{error}</p>}<section><div className="placement-section-heading"><span>01</span><div><h3>Preferências</h3><p>Corrige apenas quando necessário; todas as alterações ficam auditadas.</p></div></div><label>Turmas por ordem<small>Separadas por vírgulas, por exemplo: 7, 5, 4</small><input value={destinationText} onChange={event=>setDestinationText(event.target.value)}/></label></section>
 <section><div className="placement-section-heading"><span>02</span><div><h3>Informação adicional</h3><p>Texto submetido pelo estudante, sem categorias sugeridas.</p></div></div><blockquote className="student-confidential-note">{student.notes||"O estudante não enviou informação adicional."}</blockquote>{student.notes&&<fieldset className="validation-options"><legend>Justificação validada pela CC</legend>{Object.entries(validationLabels).map(([value,label])=><label key={value} className={validationType===value?"is-selected":""}><input type="radio" name="validation" value={value} checked={validationType===value} onChange={()=>setValidationType(value as ValidationType)}/><span>{label}</span></label>)}</fieldset>}{validationType==="other"&&<label>Descrição de “Outro”<textarea value={validationNote} onChange={event=>setValidationNote(event.target.value)} placeholder="Descreve a justificação validada pela CC."/></label>}<label>Registo administrativo<small>Obrigatório para guardar alterações.</small><textarea value={reason} onChange={event=>setReason(event.target.value)} placeholder="Indica o motivo da decisão administrativa."/></label><button className="button button--primary placement-save" onClick={()=>void save()} disabled={saving}><Save/>{saving?"A guardar…":"Guardar alterações"}</button></section>
 {move&&proposal?.status==="draft"&&!proposal.invalidated_at&&<section><div className="placement-section-heading"><span>03</span><div><h3>Revisão da colocação</h3><p>Um destino manual tem de respeitar as preferências e o equilíbrio.</p></div></div><label>Destino final<select value={manualDestination} onChange={event=>setManualDestination(Number(event.target.value))}><option value={student.class_id}>Turma {student.class_id} · origem</option>{destinations.map(item=><option key={item.destination_class} value={item.destination_class}>Turma {item.destination_class} · {item.rank}.ª preferência</option>)}</select></label><button className="button button--secondary" onClick={()=>void override()} disabled={saving}><Save/>Guardar destino manual</button></section>}</aside></div>
}
