"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AlignLeft, CheckCircle2, CircleDot, Eye, EyeOff, GraduationCap, Inbox, LoaderCircle, LockKeyhole, MessageSquareReply, MessageSquareText, Plus, Send, ShieldCheck, Tags, UserRound, X } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { AppToast, ToastKind } from "@/components/app-toast";
import { AuthGuard } from "@/components/auth-guard";
import { FormLabel } from "@/components/form-label";
import { RichTextContent, RichTextEditor } from "@/components/rich-text-editor";
import { useAuth } from "@/components/auth-context";
import { ModuleGuard } from "@/components/module-guard";
import { useModuleEnabled } from "@/components/use-module-enabled";
import { richTextPlainText, sanitizeRichTextHtml } from "@/lib/announcement-content";
import styles from "@/components/requests-center.module.css";

type DateInput = string | number;
type RequestItem = { id: string; subject: string; message: string; category: string; status: string; anonymous: boolean; authorName: string; unitId: string; unitName: string; response: string; responseVisibility: string; createdAt: DateInput };
type Unit = { id: string; code: string; name: string };
type Notice = { kind: ToastKind; message: string } | null;
const categories: Record<string, string> = { suggestion: "Sugestão", problem: "Problema", curricular_unit: "Unidade curricular", facilities: "Instalações", academic: "Assunto académico", other: "Outro" };
const statuses: Record<string, string> = { received: "Recebido", reviewing: "Em análise", forwarded: "Encaminhado", resolved: "Resolvido" };
function first(raw: Record<string, unknown>, ...keys: string[]) { for (const key of keys) if (raw[key] != null) return raw[key]; return undefined; }
function dateInput(raw: unknown): DateInput { return typeof raw === "number" ? raw : String(raw || new Date().toISOString()); }
function formatCreatedAt(value: DateInput) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "Data por confirmar" : new Intl.DateTimeFormat("pt-PT", { dateStyle: "medium", timeStyle: "short" }).format(date); }
function normalise(raw: Record<string, unknown>): RequestItem { const unit = (raw.unit && typeof raw.unit === "object" ? raw.unit : {}) as Record<string, unknown>; const submitter = (raw.submitter && typeof raw.submitter === "object" ? raw.submitter : {}) as Record<string, unknown>; const anonymous = Boolean(first(raw, "anonymous", "isAnonymous", "is_anonymous")); return { id: String(raw.id), subject: String(first(raw, "subject", "title") || "Pedido"), message: String(first(raw, "message", "body", "content") || ""), category: String(raw.category || "other"), status: String(raw.status || "received"), anonymous, authorName: anonymous ? "Envio anónimo" : String(first(raw, "authorName", "author_name") ?? first(submitter, "fullName", "full_name") ?? "Estudante"), unitId: String(first(raw, "unitId", "unit_id") ?? unit.id ?? ""), unitName: String(first(raw, "unitName", "unit_name") ?? unit.name ?? ""), response: String(first(raw, "response", "publicResponse", "public_response") || ""), responseVisibility: String(first(raw, "responseVisibility", "response_visibility") || "private"), createdAt: dateInput(first(raw, "createdAt", "created_at")) }; }

export function RequestsCenter() {
  const { user } = useAuth(); const managementEnabled = useModuleEnabled("requests.management"); const canManage = managementEnabled && (user?.role === "admin" || Boolean(user?.commissionPosition));
  const [requests, setRequests] = useState<RequestItem[]>([]); const [units, setUnits] = useState<Unit[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState<Notice>(null);
  const [statusFilter, setStatusFilter] = useState("all"); const [responses, setResponses] = useState<Record<string, string>>({}); const [responseVisibility, setResponseVisibility] = useState<Record<string, string>>({}); const [updatingId, setUpdatingId] = useState<string | null>(null);
  const [composerOpen, setComposerOpen] = useState(false); const [managingId, setManagingId] = useState<string | null>(null);
  const [form, setForm] = useState({ subject: "", message: "", category: "suggestion", unitId: "", anonymous: false, responseVisibility: "private" });
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch(canManage ? "/api/requests?scope=management" : "/api/requests", { cache: "no-store" }); const data = await response.json() as { requests?: Record<string, unknown>[]; units?: Record<string, unknown>[]; curricularUnits?: Record<string, unknown>[]; error?: string }; if (!response.ok) throw new Error(data.error || "Não foi possível carregar os pedidos."); const items = (data.requests || []).map(normalise); setRequests(items); setUnits((data.units || data.curricularUnits || []).map(raw => ({ id: String(raw.id), code: String(raw.code || ""), name: String(raw.name || "") }))); setResponses(Object.fromEntries(items.map(item => [item.id, item.response]))); setResponseVisibility(Object.fromEntries(items.map(item => [item.id, item.responseVisibility]))); } catch (error) { setNotice({ kind: "error", message: error instanceof Error ? error.message : "Não foi possível carregar os pedidos." }); } finally { setLoading(false); } }, [canManage]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => requests.filter(item => statusFilter === "all" || item.status === statusFilter).sort((a, b) => +new Date(b.createdAt) - +new Date(a.createdAt)), [requests, statusFilter]);
  const messageLength = richTextPlainText(form.message).length;
  const submit = async (event: FormEvent) => { event.preventDefault(); if (messageLength < 20 || messageLength > 5000) { setNotice({ kind: "warning", message: messageLength < 20 ? "A mensagem deve ter pelo menos 20 caracteres." : "A mensagem não pode ultrapassar 5000 caracteres." }); return; } setSaving(true); try { const response = await fetch("/api/requests", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, message: sanitizeRichTextHtml(form.message), unitId: form.unitId || null }) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error || "Não foi possível enviar o pedido."); setForm({ subject: "", message: "", category: "suggestion", unitId: "", anonymous: false, responseVisibility: "private" }); setComposerOpen(false); setNotice({ kind: "success", message: "Pedido enviado à Comissão de Curso." }); await load(); } catch (error) { setNotice({ kind: "error", message: error instanceof Error ? error.message : "Não foi possível enviar o pedido." }); } finally { setSaving(false); } };
  const update = async (id: string, status: string) => { const responseHtml = sanitizeRichTextHtml(responses[id] || ""); if (richTextPlainText(responseHtml).length > 5000) { setNotice({ kind: "warning", message: "A resposta não pode ultrapassar 5000 caracteres." }); return; } setUpdatingId(id); try { const response = await fetch("/api/requests", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, status, response: responseHtml, responseVisibility: responseVisibility[id] || "private" }) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error || "Não foi possível atualizar o pedido."); setNotice({ kind: "success", message: "Pedido atualizado." }); await load(); } catch (error) { setNotice({ kind: "error", message: error instanceof Error ? error.message : "Não foi possível atualizar o pedido." }); } finally { setUpdatingId(null); } };
  return <AuthGuard><ModuleGuard moduleKey="requests.submission"><AppShell active="requests" breadcrumb="Pedidos e sugestões">
    {notice && <AppToast kind={notice.kind} message={notice.message} onDismiss={() => setNotice(null)} />}
    <section className={styles.hero}><div className={styles.heroIcon}><Inbox /></div><div><span className="eyebrow">Participação estudantil</span><h1>Pedidos e sugestões</h1><p>Partilha uma sugestão, problema ou preocupação com a Comissão de Curso.</p></div><button className={styles.createButton} type="button" aria-expanded={composerOpen} onClick={() => setComposerOpen((open) => !open)}>{composerOpen ? <X /> : <Plus />}{composerOpen ? "Fechar" : "Novo pedido"}</button></section>
    <div className={styles.splitLayout}>
      {composerOpen && <form className={`${styles.panel} ${styles.form}`} onSubmit={submit}><div className={styles.formHeading}><h2>Novo pedido</h2><p>Preenche apenas o essencial. Podes escolher como o pedido e a resposta serão tratados.</p></div><div className={styles.formGrid}>
        <label className={styles.full}><FormLabel icon={MessageSquareText}>Assunto</FormLabel><input required maxLength={160} value={form.subject} onChange={e => setForm({ ...form, subject: e.target.value })} placeholder="Resume o assunto numa frase" /></label>
        <label><FormLabel icon={Tags}>Categoria</FormLabel><select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}>{Object.entries(categories).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label>
        <label><FormLabel icon={GraduationCap} optional>Unidade curricular</FormLabel><select value={form.unitId} onChange={e => setForm({ ...form, unitId: e.target.value })}><option value="">Assunto geral</option>{units.map(unit => <option value={unit.id} key={unit.id}>{unit.code} · {unit.name}</option>)}</select></label>
        <label className={styles.full}><FormLabel icon={AlignLeft}>Mensagem</FormLabel><RichTextEditor value={form.message} onChange={(message) => setForm((current) => ({ ...current, message }))} ariaLabel="Mensagem do pedido" placeholder="Explica o que aconteceu ou o que sugeres…" maxLength={5000} onInvalidLink={() => setNotice({ kind: "warning", message: "Indica uma ligação válida iniciada por https://." })} /></label>
        <fieldset className={`${styles.full} ${styles.privacyOptions}`}><legend><FormLabel icon={UserRound}>Privacidade</FormLabel></legend><label className={!form.anonymous ? styles.optionSelected : ""}><input type="radio" name="identity" checked={!form.anonymous} onChange={() => setForm({ ...form, anonymous: false })} /><UserRound /><span><strong>Enviar com identificação</strong><small>A Comissão de Curso saberá quem enviou.</small></span></label><label className={form.anonymous ? styles.optionSelected : ""}><input type="radio" name="identity" checked={form.anonymous} onChange={() => setForm({ ...form, anonymous: true })} /><EyeOff /><span><strong>Enviar anonimamente</strong><small>A tua identidade não será apresentada aos membros que tratam o pedido.</small></span></label></fieldset>
        <fieldset className={`${styles.full} ${styles.privacyOptions}`}><legend><FormLabel icon={Eye}>Visibilidade da resposta</FormLabel></legend><label className={form.responseVisibility === "private" ? styles.optionSelected : ""}><input type="radio" name="answer" checked={form.responseVisibility === "private"} onChange={() => setForm({ ...form, responseVisibility: "private" })} /><LockKeyhole /><span><strong>Resposta privada</strong><small>Visível apenas para ti e para a Comissão de Curso.</small></span></label><label className={form.responseVisibility === "public" ? styles.optionSelected : ""}><input type="radio" name="answer" checked={form.responseVisibility === "public"} onChange={() => setForm({ ...form, responseVisibility: "public" })} /><Eye /><span><strong>Resposta pública</strong><small>Pode ajudar outros estudantes, sem revelar a tua identidade.</small></span></label></fieldset>
      </div><footer className={styles.formActions}><button className="button button--secondary" type="button" onClick={() => setComposerOpen(false)}>Cancelar</button><button className="button button--primary" disabled={saving || messageLength < 20 || messageLength > 5000}>{saving ? <LoaderCircle className={styles.spin} /> : <Send />}{saving ? "A enviar…" : form.anonymous ? "Enviar anonimamente" : "Enviar pedido"}</button></footer></form>}
      <section className={styles.panel}><div className={styles.sectionHead}><div><h2>{canManage ? "Pedidos recebidos" : "Os meus pedidos"}</h2><p>{canManage ? "Acompanha e responde aos pedidos dos estudantes." : "Acompanha o estado e as respostas."}</p></div><label><span className={styles.srOnly}>Estado</span><select value={statusFilter} onChange={e => setStatusFilter(e.target.value)}><option value="all">Todos os estados</option>{Object.entries(statuses).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label></div>
        {loading ? <div className={styles.loading}><LoaderCircle className={styles.spin} />A carregar pedidos…</div> : visible.length === 0 ? <div className={styles.empty}><CheckCircle2 /><strong>Não existem pedidos neste estado</strong><span>Os novos pedidos aparecerão aqui.</span></div> : <div className={styles.requestList}>{visible.map(item => <article className={styles.requestCard} key={item.id}><header><div className={styles.badgeRow}><span className={styles.badge}>{categories[item.category] || item.category}</span><span className={styles.statusBadge}>{statuses[item.status] || item.status}</span>{item.responseVisibility === "private" && <span className={styles.softBadge}><LockKeyhole />Resposta privada</span>}</div><time>{formatCreatedAt(item.createdAt)}</time></header><h3>{item.subject}</h3><RichTextContent value={item.message} className={styles.requestMessage} /><div className={styles.requestMeta}><small>{item.anonymous ? <><EyeOff /> Envio anónimo</> : <><UserRound /> {item.authorName}</>} {item.unitName && ` · ${item.unitName}`}</small>{canManage && <button className={styles.manageToggle} type="button" aria-expanded={managingId === item.id} onClick={() => setManagingId((current) => current === item.id ? null : item.id)}><MessageSquareReply />{managingId === item.id ? "Fechar gestão" : "Responder e gerir"}</button>}</div>
          {item.response && !canManage && <div className={styles.answer}><MessageSquareReply /><div><strong>Resposta da Comissão de Curso</strong><RichTextContent value={item.response} className={styles.answerContent} /></div></div>}
          {canManage && managingId === item.id && <div className={styles.manageRequest}><label><FormLabel icon={CircleDot}>Estado</FormLabel><select value={item.status} onChange={e => void update(item.id, e.target.value)} disabled={updatingId === item.id}>{Object.entries(statuses).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label><label className={styles.wide}><FormLabel icon={MessageSquareReply}>Resposta</FormLabel><RichTextEditor value={responses[item.id] || ""} onChange={(response) => setResponses((current) => ({ ...current, [item.id]: response }))} ariaLabel={`Resposta ao pedido ${item.subject}`} placeholder="Escreve a resposta da Comissão de Curso…" maxLength={5000} minHeight="compact" onInvalidLink={() => setNotice({ kind: "warning", message: "Indica uma ligação válida iniciada por https://." })} /></label><label><FormLabel icon={Eye}>Visibilidade</FormLabel><select value={responseVisibility[item.id] || "private"} onChange={e => setResponseVisibility({ ...responseVisibility, [item.id]: e.target.value })}><option value="private">Privada</option><option value="public">Pública</option></select></label><button className="button button--primary" onClick={() => void update(item.id, item.status)} disabled={updatingId === item.id || richTextPlainText(responses[item.id] || "").length > 5000}>{updatingId === item.id ? <LoaderCircle className={styles.spin} /> : <ShieldCheck />}Guardar resposta</button></div>}
        </article>)}</div>}
      </section>
    </div>
  </AppShell></ModuleGuard></AuthGuard>;
}
