"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AlignLeft, CheckCircle2, CircleDot, Eye, EyeOff, GraduationCap, Inbox, LoaderCircle, LockKeyhole, MessageSquareReply, MessageSquareText, Plus, Send, ShieldCheck, Tags, Trash2, TriangleAlert, UserRound, X } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { AppToast, ToastKind } from "@/components/app-toast";
import { AuthGuard } from "@/components/auth-guard";
import { FormLabel } from "@/components/form-label";
import { RichTextContent, RichTextEditor } from "@/components/rich-text-editor";
import { useAuth } from "@/components/auth-context";
import { useI18n } from "@/components/i18n-context";
import { ModuleGuard } from "@/components/module-guard";
import { PersonName } from "@/components/person-name";
import { useModuleEnabled } from "@/components/use-module-enabled";
import { richTextPlainText, sanitizeRichTextHtml } from "@/lib/announcement-content";
import { personDisplay } from "@/lib/person-display";
import styles from "@/components/requests-center.module.css";

type DateInput = string | number;
type RequestItem = { id: string; subject: string; message: string; category: string; status: string; anonymous: boolean; authorName: string; authorId: string; authorEmail: string; authorStudentNumber: string; unitId: string; unitName: string; response: string; responseVisibility: string; createdAt: DateInput; isOwn: boolean };
type Unit = { id: string; code: string; name: string };
type Notice = { kind: ToastKind; message: string } | null;
function first(raw: Record<string, unknown>, ...keys: string[]) { for (const key of keys) if (raw[key] != null) return raw[key]; return undefined; }
function dateInput(raw: unknown): DateInput { return typeof raw === "number" ? raw : String(raw || new Date().toISOString()); }
function formatCreatedAt(value: DateInput, locale: string, unknownDate: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? unknownDate : new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short" }).format(date); }
function normalise(raw: Record<string, unknown>, anonymousAuthor: string, studentAuthor: string, fallbackSubject: string): RequestItem { const unit = (raw.unit && typeof raw.unit === "object" ? raw.unit : {}) as Record<string, unknown>; const submitter = (raw.submitter && typeof raw.submitter === "object" ? raw.submitter : {}) as Record<string, unknown>; const anonymous = Boolean(first(raw, "anonymous", "isAnonymous", "is_anonymous")); return { id: String(raw.id), subject: String(first(raw, "subject", "title") || fallbackSubject), message: String(first(raw, "message", "body", "content") || ""), category: String(raw.category || "other"), status: String(raw.status || "received"), anonymous, authorName: anonymous ? anonymousAuthor : String(first(raw, "authorName", "author_name") ?? first(submitter, "fullName", "full_name") ?? studentAuthor), authorId: String(first(submitter, "id") ?? ""), authorEmail: String(first(submitter, "email") ?? ""), authorStudentNumber: String(first(submitter, "studentNumber", "student_number") ?? ""), unitId: String(first(raw, "unitId", "unit_id") ?? unit.id ?? ""), unitName: String(first(raw, "unitName", "unit_name") ?? unit.name ?? ""), response: String(first(raw, "response", "publicResponse", "public_response") || ""), responseVisibility: String(first(raw, "responseVisibility", "response_visibility") || "private"), createdAt: dateInput(first(raw, "createdAt", "created_at")), isOwn: Boolean(first(raw, "isOwn", "is_own")) }; }

export function RequestsCenter() {
  const { locale, t } = useI18n();
  const dateLocale = locale === "en" ? "en-GB" : "pt-PT";
  const categories = useMemo<Record<string, string>>(() => ({ suggestion: t("requests.category.suggestion"), problem: t("requests.category.problem"), curricular_unit: t("requests.category.curricularUnit"), facilities: t("requests.category.facilities"), academic: t("requests.category.academic"), other: t("requests.category.other") }), [t]);
  const statuses = useMemo<Record<string, string>>(() => ({ received: t("requests.status.received"), reviewing: t("requests.status.reviewing"), forwarded: t("requests.status.forwarded"), resolved: t("requests.status.resolved"), closed: t("requests.status.closed") }), [t]);
  const { user } = useAuth(); const managementEnabled = useModuleEnabled("requests.management"); const canManage = managementEnabled && (user?.role === "admin" || Boolean(user?.commissionPosition));
  const [requests, setRequests] = useState<RequestItem[]>([]); const [units, setUnits] = useState<Unit[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState<Notice>(null);
  const [statusFilter, setStatusFilter] = useState("all"); const [responses, setResponses] = useState<Record<string, string>>({}); const [responseVisibility, setResponseVisibility] = useState<Record<string, string>>({}); const [updatingId, setUpdatingId] = useState<string | null>(null);
  const [composerOpen, setComposerOpen] = useState(false); const [managingId, setManagingId] = useState<string | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<RequestItem | null>(null); const [deletingId, setDeletingId] = useState<string | null>(null); const [deleteError, setDeleteError] = useState("");
  const [form, setForm] = useState({ subject: "", message: "", category: "suggestion", unitId: "", anonymous: false, responseVisibility: "private" });
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch(canManage ? "/api/requests?scope=management" : "/api/requests", { cache: "no-store" }); const data = await response.json() as { requests?: Record<string, unknown>[]; units?: Record<string, unknown>[]; curricularUnits?: Record<string, unknown>[]; error?: string }; if (!response.ok) throw new Error(data.error || t("requests.loadError")); const items = (data.requests || []).map(raw => normalise(raw, t("requests.anonymousAuthor"), t("requests.studentAuthor"), t("requests.fallbackSubject"))); setRequests(items); setUnits((data.units || data.curricularUnits || []).map(raw => ({ id: String(raw.id), code: String(raw.code || ""), name: String(raw.name || "") }))); setResponses(Object.fromEntries(items.map(item => [item.id, item.response]))); setResponseVisibility(Object.fromEntries(items.map(item => [item.id, item.responseVisibility]))); } catch (error) { setNotice({ kind: "error", message: error instanceof Error ? error.message : t("requests.loadError") }); } finally { setLoading(false); } }, [canManage, t]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => requests.filter(item => statusFilter === "all" || item.status === statusFilter).sort((a, b) => +new Date(b.createdAt) - +new Date(a.createdAt)), [requests, statusFilter]);
  const messageLength = richTextPlainText(form.message).length;
  const submit = async (event: FormEvent) => { event.preventDefault(); if (messageLength < 20 || messageLength > 5000) { setNotice({ kind: "warning", message: messageLength < 20 ? t("requests.messageTooShort") : t("requests.messageTooLong") }); return; } setSaving(true); try { const response = await fetch("/api/requests", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, message: sanitizeRichTextHtml(form.message), unitId: form.unitId || null }) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error || t("requests.sendError")); setForm({ subject: "", message: "", category: "suggestion", unitId: "", anonymous: false, responseVisibility: "private" }); setComposerOpen(false); setNotice({ kind: "success", message: t("requests.sendSuccess") }); await load(); } catch (error) { setNotice({ kind: "error", message: error instanceof Error ? error.message : t("requests.sendError") }); } finally { setSaving(false); } };
  const update = async (id: string, status: string) => { const responseHtml = sanitizeRichTextHtml(responses[id] || ""); if (richTextPlainText(responseHtml).length > 5000) { setNotice({ kind: "warning", message: t("requests.responseTooLong") }); return; } setUpdatingId(id); try { const response = await fetch("/api/requests", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, status, response: responseHtml, responseVisibility: responseVisibility[id] || "private" }) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error || t("requests.updateError")); setNotice({ kind: "success", message: t("requests.updateSuccess") }); await load(); } catch (error) { setNotice({ kind: "error", message: error instanceof Error ? error.message : t("requests.updateError") }); } finally { setUpdatingId(null); } };
  const remove = async () => { if (!deleteTarget) return; setDeletingId(deleteTarget.id); setDeleteError(""); try { const response = await fetch(`/api/requests?id=${encodeURIComponent(deleteTarget.id)}`, { method: "DELETE" }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error || t("requests.deleteError")); const deletedId = deleteTarget.id; setDeleteTarget(null); setManagingId(current => current === deletedId ? null : current); setNotice({ kind: "success", message: t("requests.deleteSuccess") }); await load(); } catch (error) { setDeleteError(error instanceof Error ? error.message : t("requests.deleteError")); } finally { setDeletingId(null); } };
  return <AuthGuard><ModuleGuard moduleKey="requests.submission"><AppShell active="requests" breadcrumb={t("requests.title")}>
    {notice && <AppToast kind={notice.kind} message={notice.message} onDismiss={() => setNotice(null)} />}
    <section className={styles.hero}><div className={styles.heroIcon}><Inbox /></div><div><span className="eyebrow">{t("requests.eyebrow")}</span><h1>{t("requests.title")}</h1><p>{t("requests.intro")}</p></div><button className={styles.createButton} type="button" aria-expanded={composerOpen} onClick={() => setComposerOpen((open) => !open)}>{composerOpen ? <X /> : <Plus />}{composerOpen ? t("requests.close") : t("requests.new")}</button></section>
    <div className={styles.splitLayout}>
      {composerOpen && <form className={`${styles.panel} ${styles.form}`} onSubmit={submit}><div className={styles.formHeading}><h2>{t("requests.form.title")}</h2><p>{t("requests.form.intro")}</p></div><div className={styles.formGrid}>
        <label className={styles.full}><FormLabel icon={MessageSquareText}>{t("requests.form.subject")}</FormLabel><input required maxLength={160} value={form.subject} onChange={e => setForm({ ...form, subject: e.target.value })} placeholder={t("requests.form.subjectPlaceholder")} /></label>
        <label><FormLabel icon={Tags}>{t("requests.form.category")}</FormLabel><select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}>{Object.entries(categories).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label>
        <label><FormLabel icon={GraduationCap} optional>{t("requests.form.unit")}</FormLabel><select value={form.unitId} onChange={e => setForm({ ...form, unitId: e.target.value })}><option value="">{t("requests.form.general")}</option>{units.map(unit => <option value={unit.id} key={unit.id}>{unit.code} · {unit.name}</option>)}</select></label>
        <label className={styles.full}><FormLabel icon={AlignLeft}>{t("requests.form.message")}</FormLabel><RichTextEditor value={form.message} onChange={(message) => setForm((current) => ({ ...current, message }))} ariaLabel={t("requests.form.messageAria")} placeholder={t("requests.form.messagePlaceholder")} maxLength={5000} onInvalidLink={() => setNotice({ kind: "warning", message: t("requests.invalidLink") })} /></label>
        <fieldset className={`${styles.full} ${styles.privacyOptions}`}><legend><FormLabel icon={UserRound}>{t("requests.form.privacy")}</FormLabel></legend><label className={!form.anonymous ? styles.optionSelected : ""}><input type="radio" name="identity" checked={!form.anonymous} onChange={() => setForm({ ...form, anonymous: false })} /><UserRound /><span><strong>{t("requests.form.identified")}</strong><small>{t("requests.form.identifiedHelp")}</small></span></label><label className={form.anonymous ? styles.optionSelected : ""}><input type="radio" name="identity" checked={form.anonymous} onChange={() => setForm({ ...form, anonymous: true })} /><EyeOff /><span><strong>{t("requests.form.anonymous")}</strong><small>{t("requests.form.anonymousHelp")}</small></span></label></fieldset>
        <fieldset className={`${styles.full} ${styles.privacyOptions}`}><legend><FormLabel icon={Eye}>{t("requests.form.responseVisibility")}</FormLabel></legend><label className={form.responseVisibility === "private" ? styles.optionSelected : ""}><input type="radio" name="answer" checked={form.responseVisibility === "private"} onChange={() => setForm({ ...form, responseVisibility: "private" })} /><LockKeyhole /><span><strong>{t("requests.form.private")}</strong><small>{t("requests.form.privateHelp")}</small></span></label><label className={form.responseVisibility === "public" ? styles.optionSelected : ""}><input type="radio" name="answer" checked={form.responseVisibility === "public"} onChange={() => setForm({ ...form, responseVisibility: "public" })} /><Eye /><span><strong>{t("requests.form.public")}</strong><small>{t("requests.form.publicHelp")}</small></span></label></fieldset>
      </div><footer className={styles.formActions}><button className="button button--secondary" type="button" onClick={() => setComposerOpen(false)}>{t("requests.form.cancel")}</button><button className="button button--primary" disabled={saving || messageLength < 20 || messageLength > 5000}>{saving ? <LoaderCircle className={styles.spin} /> : <Send />}{saving ? t("requests.form.sending") : form.anonymous ? t("requests.form.sendAnonymous") : t("requests.form.send")}</button></footer></form>}
      <section className={styles.panel}><div className={styles.sectionHead}><div><h2>{canManage ? t("requests.list.received") : t("requests.list.mine")}</h2><p>{canManage ? t("requests.list.managementIntro") : t("requests.list.mineIntro")}</p></div><label><span className={styles.srOnly}>{t("requests.list.filterAria")}</span><select value={statusFilter} onChange={e => setStatusFilter(e.target.value)}><option value="all">{t("requests.list.allStatuses")}</option>{Object.entries(statuses).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label></div>
        {loading ? <div className={styles.loading}><LoaderCircle className={styles.spin} />{t("requests.loading")}</div> : visible.length === 0 ? <div className={styles.empty}><CheckCircle2 /><strong>{t("requests.empty.title")}</strong><span>{t("requests.empty.body")}</span></div> : <div className={styles.requestList}>{visible.map(item => { const author = personDisplay({ fullName: item.authorName, id: item.authorId, email: item.authorEmail, studentNumber: item.authorStudentNumber, anonymous: item.anonymous, anonymousLabel: t("requests.anonymousSubmission") }, { revealIdentifier: canManage, locale }); return <article className={styles.requestCard} key={item.id}><header><div className={styles.badgeRow}><span className={styles.badge}>{categories[item.category] || item.category}</span><span className={styles.statusBadge}>{statuses[item.status] || item.status}</span>{item.responseVisibility === "private" && <span className={styles.softBadge}><LockKeyhole />{t("requests.privateResponse")}</span>}</div><time>{formatCreatedAt(item.createdAt, dateLocale, t("requests.dateUnknown"))}</time></header><h3>{item.subject}</h3><RichTextContent value={item.message} className={styles.requestMessage} /><div className={styles.requestMeta}><small>{item.anonymous ? <EyeOff /> : <UserRound />} <PersonName person={author} /> {item.unitName && ` · ${item.unitName}`}</small><div className={styles.requestActions}>{canManage && <button className={styles.manageAction} type="button" aria-expanded={managingId === item.id} onClick={() => setManagingId((current) => current === item.id ? null : item.id)}><MessageSquareReply />{managingId === item.id ? t("requests.closeManagement") : t("requests.manage")}</button>}{(canManage || item.isOwn) && <button className={styles.deleteAction} type="button" onClick={() => { setDeleteError(""); setDeleteTarget(item); }}><Trash2 />{t("requests.delete")}</button>}</div></div>
          {item.response && !canManage && <div className={styles.answer}><MessageSquareReply /><div><strong>{t("requests.answer.title")}</strong><RichTextContent value={item.response} className={styles.answerContent} /></div></div>}
          {canManage && managingId === item.id && <div className={styles.manageRequest}><label><FormLabel icon={CircleDot}>{t("requests.management.status")}</FormLabel><select value={item.status} onChange={e => void update(item.id, e.target.value)} disabled={updatingId === item.id}>{Object.entries(statuses).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label><label className={styles.wide}><FormLabel icon={MessageSquareReply}>{t("requests.management.response")}</FormLabel><RichTextEditor value={responses[item.id] || ""} onChange={(response) => setResponses((current) => ({ ...current, [item.id]: response }))} ariaLabel={t("requests.management.responseAria", { subject: item.subject })} placeholder={t("requests.management.responsePlaceholder")} maxLength={5000} minHeight="compact" onInvalidLink={() => setNotice({ kind: "warning", message: t("requests.invalidLink") })} /></label><label><FormLabel icon={Eye}>{t("requests.management.visibility")}</FormLabel><select value={responseVisibility[item.id] || "private"} onChange={e => setResponseVisibility({ ...responseVisibility, [item.id]: e.target.value })}><option value="private">{t("requests.management.private")}</option><option value="public">{t("requests.management.public")}</option></select></label><button className="button button--primary" onClick={() => void update(item.id, item.status)} disabled={updatingId === item.id || richTextPlainText(responses[item.id] || "").length > 5000}>{updatingId === item.id ? <LoaderCircle className={styles.spin} /> : <ShieldCheck />}{updatingId === item.id ? t("requests.management.saving") : t("requests.management.save")}</button></div>}
        </article>; })}</div>}
      </section>
    </div>
    {deleteTarget && <div className={styles.dialogBackdrop} role="presentation" onMouseDown={event => { if (!deletingId && event.currentTarget === event.target) setDeleteTarget(null); }}><section className={styles.deleteDialog} role="dialog" aria-modal="true" aria-labelledby="delete-request-title"><header><span className={styles.deleteIcon}><Trash2 /></span><div><span className="eyebrow">{t("requests.delete.eyebrow")}</span><h2 id="delete-request-title">{t("requests.delete.title")}</h2><p>{t("requests.delete.intro")}</p></div></header><div className={styles.deleteSummary}><span>{t("requests.delete.selected")}</span><strong>{deleteTarget.subject}</strong></div><div className={styles.deleteWarning}><TriangleAlert /><p>{t("requests.delete.warning")}</p></div>{deleteError && <p className={styles.deleteError} role="alert">{deleteError}</p>}<footer><button className="button button--secondary" type="button" disabled={Boolean(deletingId)} onClick={() => setDeleteTarget(null)}>{t("requests.delete.cancel")}</button><button className={styles.deleteConfirm} type="button" disabled={Boolean(deletingId)} onClick={() => void remove()}>{deletingId ? <LoaderCircle className={styles.spin} /> : <Trash2 />}{deletingId ? t("requests.delete.deleting") : t("requests.delete.confirm")}</button></footer></section></div>}
  </AppShell></ModuleGuard></AuthGuard>;
}
