/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import {useCallback,useEffect,useState} from "react";
import {ArrowDown,ArrowUp,Check,Plus,Save,Trash2} from "lucide-react";

type PreferenceData={student:{classId:number;preference:"stay"|"move";notes:string;destinations:number[]};activeClasses:number[];settings:{closeAt?:string};serverNow:number};

export function StudentPreferencePanel(){
 const [data,setData]=useState<PreferenceData|null>(null),[destinations,setDestinations]=useState<number[]>([]),[notes,setNotes]=useState(""),[saving,setSaving]=useState(false),[notice,setNotice]=useState("");
 const load=useCallback(async()=>{const response=await fetch("/api/student/destinations",{cache:"no-store"});if(!response.ok)return;const result=await response.json() as PreferenceData;setData(result);setDestinations(result.student.destinations);setNotes(result.student.notes)},[]);
 useEffect(()=>{void load()},[load]);
 if(!data||data.serverNow<Date.parse(data.settings.closeAt||""))return null;
 const alternatives=data.activeClasses.filter(id=>id!==data.student.classId),moving=destinations.length>0;
 const update=(index:number,value:number)=>setDestinations(current=>current.map((item,i)=>i===index?value:item));
 const shift=(index:number,direction:-1|1)=>setDestinations(current=>current.map((value,i)=>i===index+direction?current[index]:i===index?current[index+direction]:value));
 async function save(){setSaving(true);setNotice("");const response=await fetch("/api/student/destinations",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({destinations,notes})}),result=await response.json() as {error?:string};setNotice(response.ok?"Preferências guardadas com sucesso.":result.error||"Não foi possível guardar.");setSaving(false)}
 return <section className="student-preferences" aria-labelledby="student-preferences-title"><header><div><span className="eyebrow">A tua colocação</span><h2 id="student-preferences-title">Turma {data.student.classId} · preferências</h2><p>Este painel acompanha-te enquanto consultas a composição das outras turmas.</p></div><span className={`preference-state ${moving?"is-move":"is-stay"}`}>{moving?"Pretendes mudar":"Permaneces na turma"}</span></header><div className="student-preferences__body"><div className="student-preferences__choice"><button className={!moving?"is-active":""} onClick={()=>setDestinations([])}><Check/>Ficar na Turma {data.student.classId}</button><button className={moving?"is-active":""} onClick={()=>setDestinations(current=>current.length?current:[alternatives[0]])}>Indicar alternativas</button></div>{moving&&<div className="student-preferences__ranking"><div className="preference-intro"><strong>Ordem de preferência</strong><span>Se nenhuma alternativa for possível, manténs a Turma {data.student.classId}.</span></div>{destinations.map((destination,index)=><div className="student-preferences__row" key={destination}><span>{index+1}.ª</span><select aria-label={`${index+1}.ª preferência`} value={destination} onChange={event=>update(index,Number(event.target.value))}>{alternatives.filter(id=>!destinations.includes(id)||id===destination).map(id=><option value={id} key={id}>Turma {id}</option>)}</select><div><button aria-label="Subir preferência" disabled={index===0} onClick={()=>shift(index,-1)}><ArrowUp/></button><button aria-label="Descer preferência" disabled={index===destinations.length-1} onClick={()=>shift(index,1)}><ArrowDown/></button><button aria-label="Remover preferência" onClick={()=>setDestinations(current=>current.filter((_,i)=>i!==index))}><Trash2/></button></div></div>)}<button className="add-preference" disabled={destinations.length>=alternatives.length} onClick={()=>setDestinations(current=>[...current,alternatives.find(id=>!current.includes(id))!])}><Plus/>Acrescentar alternativa</button></div>}<label className="student-preferences__notes"><span>Nota excecional <small>Opcional · apenas para situações que exijam análise manual</small></span><textarea maxLength={1000} value={notes} onChange={event=>setNotes(event.target.value)} placeholder="Ex.: situação de bullying ou dificuldade grave de integração. Partilha apenas o indispensável."/></label></div><footer>{notice&&<p role="status">{notice}</p>}<button className="button button--primary" onClick={()=>void save()} disabled={saving}><Save/>{saving?"A guardar…":"Guardar preferências"}</button></footer></section>
}
