"use client";
/* eslint-disable react-hooks/set-state-in-effect */

import { useCallback, useEffect, useState } from "react";
import { ArrowDown, ArrowUp, Check, CheckCircle2, CircleHelp, Clock3, LockKeyhole, Pencil, Plus, Send, Trash2, X } from "lucide-react";
import { AppToast } from "@/components/app-toast";
import { useI18n } from "@/components/i18n-context";

type Decision = "stay" | "move" | null;
type PreferenceData = { student: { classId: number; decision: Decision; submittedAt: number | null; notes: string; destinations: number[] }; activeClasses: number[]; settings: { preferencesOpenAt?: string; preferencesCloseAt?: string; groupLabel?: string }; serverNow: number };

export function StudentPreferencePanel() {
  const { locale, t } = useI18n();
  const [data, setData] = useState<PreferenceData | null>(null), [decision, setDecision] = useState<Decision>(null), [destinations, setDestinations] = useState<number[]>([]), [notes, setNotes] = useState(""), [editing, setEditing] = useState(true), [saving, setSaving] = useState(false), [notice, setNotice] = useState(""), [noticeError, setNoticeError] = useState(false);
  const load = useCallback(async () => { const response = await fetch("/api/student/destinations", { cache: "no-store" }); if (!response.ok) return; const result = await response.json() as PreferenceData; setData(result); setDecision(result.student.decision); setDestinations(result.student.decision === "move" ? result.student.destinations : []); setNotes(result.student.decision === "move" ? result.student.notes || "" : ""); setEditing(!result.student.submittedAt); }, []);
  useEffect(() => { void load(); }, [load]);
  if (!data) return null;
  const format = (value: number) => new Date(value).toLocaleString(locale);
  const opensAt = data.settings.preferencesOpenAt ? Date.parse(data.settings.preferencesOpenAt) : 0, closesAt = data.settings.preferencesCloseAt ? Date.parse(data.settings.preferencesCloseAt) : 0;
  const beforeOpen = Boolean(opensAt && data.serverNow < opensAt), closed = Boolean(closesAt && data.serverNow >= closesAt), locked = beforeOpen || closed, submitted = Boolean(data.student.submittedAt), moving = decision === "move";
  const alternatives = data.activeClasses.filter((id) => id !== data.student.classId);
  const helpButton = (topic: "overview" | "ranking", label: string) => <span className="preference-help-wrap"><button type="button" className="preference-help-button" aria-label={label} aria-describedby={`help-${topic}`}><CircleHelp /></button><span className="preference-help-tooltip" id={`help-${topic}`} role="tooltip">{t(topic === "overview" ? "classes.preferences.helpOverview" : "classes.preferences.helpRanking")}</span></span>;
  const shift = (index: number, direction: -1 | 1) => setDestinations((current) => current.map((value, i) => i === index + direction ? current[index] : i === index ? current[index + direction] : value));
  const chooseStay = () => { setDecision("stay"); setDestinations([]); setNotes(""); };
  const chooseMove = () => { setDecision("move"); setDestinations((current) => current.length ? current : alternatives.length ? [alternatives[0]] : []); };
  async function save() {
    if (locked) return;
    if (!decision) { setNoticeError(true); setNotice(t("classes.preferences.chooseError")); return; }
    if (decision === "move" && !destinations.length) { setNoticeError(true); setNotice(t("classes.preferences.destinationError")); return; }
    setSaving(true); setNotice("");
    const response = await fetch("/api/student/destinations", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ decision, destinations: decision === "move" ? destinations : [], notes: decision === "move" ? notes : "" }) }), result = await response.json() as { error?: string };
    setNoticeError(!response.ok); setNotice(response.ok ? t("classes.preferences.success") : result.error || t("classes.preferences.error"));
    if (response.ok) { await load(); setEditing(false); }
    setSaving(false);
  }
  const state = beforeOpen ? t("classes.preferences.state.notOpen") : closed ? t("classes.preferences.state.closed") : submitted && !editing ? t("classes.preferences.state.submitted") : editing && submitted ? t("classes.preferences.state.editing") : moving ? t("classes.preferences.state.moving") : decision === "stay" ? t("classes.preferences.state.staying") : t("classes.preferences.state.empty");
  return <>{notice && <AppToast key={`${noticeError ? "error" : "success"}:${notice}`} kind={noticeError ? "error" : "success"} message={notice} onDismiss={() => setNotice("")} />}<section className={`student-preferences${locked ? " is-locked" : ""}${submitted && !editing ? " is-submitted" : ""}`}>
    <header><div><span className="eyebrow">{t("classes.preferences.eyebrow")}</span><h2>{t("classes.preferences.title", { id: data.student.classId })}</h2><p>{data.settings.groupLabel || t("classes.preferences.window")}</p></div><div className="student-preferences__header-actions">{helpButton("overview", t("classes.preferences.helpFill"))}<span className={`preference-state ${submitted && !editing ? "is-submitted" : locked ? "is-locked" : moving ? "is-move" : "is-stay"}`}>{state}</span></div></header>
    {locked && <div className="student-preferences__deadline-closed"><LockKeyhole size={17} /><span><strong>{beforeOpen ? t("classes.preferences.notAvailable") : t("classes.preferences.state.closed")}</strong><small>{beforeOpen && opensAt ? t("classes.preferences.opensAt", { date: format(opensAt) }) : submitted ? t("classes.preferences.savedLocked") : t("classes.preferences.closedEmpty")}</small></span></div>}
    {submitted && !editing ? <div className="preference-submission-confirmation"><span><CheckCircle2 /></span><div><strong>{t("classes.preferences.submittedTitle")}</strong><p>{decision === "move" ? t(destinations.length === 1 ? "classes.preferences.moveSummary" : "classes.preferences.moveSummaryPlural", { count: destinations.length }) : t("classes.preferences.staySummary")}</p><small>{t("classes.preferences.submittedAt", { date: format(data.student.submittedAt!) })}{!closed && closesAt ? t("classes.preferences.editUntil", { date: format(closesAt) }) : ""}</small></div>{!locked && <button type="button" className="button button--secondary" onClick={() => setEditing(true)}><Pencil />{t("classes.preferences.edit")}</button>}</div> : <>
      <div className="student-preferences__body">
        <div className="student-preferences__choice-column"><div className="student-preferences__choice"><button type="button" className={decision === "stay" ? "is-active" : ""} disabled={locked} onClick={chooseStay}><Check />{t("classes.preferences.keep", { id: data.student.classId })}</button><button type="button" className={moving ? "is-active" : ""} disabled={locked} onClick={chooseMove}>{t("classes.preferences.change")}</button></div></div>
        {decision === "stay" && <aside className="preference-side-guide"><span className="preference-side-guide__icon"><Check /></span><div><strong>{t("classes.preferences.stayTitle")}</strong><p>{t("classes.preferences.stayHint")}</p></div></aside>}
        {moving && <div className="student-preferences__ranking"><div className="preference-intro"><strong>{t("classes.preferences.ranking")}</strong><div>{helpButton("ranking", t("classes.preferences.rankingHelp"))}</div></div>{destinations.map((destination, index) => <div className="preference-destination" key={`${destination}-${index}`}><div className="student-preferences__row"><span>{t("classes.preferences.rank", { rank: index + 1 })}</span><select value={destination} disabled={locked} onChange={(event) => setDestinations((current) => current.map((value, i) => i === index ? Number(event.target.value) : value))}>{alternatives.filter((id) => !destinations.includes(id) || id === destination).map((id) => <option key={id} value={id}>{t("classes.common.class", { id })}</option>)}</select><div><button type="button" aria-label={t("classes.preferences.up")} disabled={locked || !index} onClick={() => shift(index, -1)}><ArrowUp /></button><button type="button" aria-label={t("classes.preferences.down")} disabled={locked || index === destinations.length - 1} onClick={() => shift(index, 1)}><ArrowDown /></button><button type="button" aria-label={t("classes.preferences.remove")} disabled={locked} onClick={() => setDestinations((current) => current.filter((_, i) => i !== index))}><Trash2 /></button></div></div></div>)}<button type="button" className="add-preference" disabled={locked || destinations.length >= alternatives.length} onClick={() => setDestinations((current) => [...current, alternatives.find((id) => !current.includes(id))!])}><Plus />{t("classes.preferences.add")}</button></div>}
        {moving && <label className="student-additional-info"><span><strong>{t("classes.preferences.notes")}</strong><small>{t("classes.preferences.notesHint")}</small></span><textarea maxLength={1000} value={notes} disabled={locked} onChange={(event) => setNotes(event.target.value)} placeholder={t("classes.preferences.notesPlaceholder")} /></label>}
      </div><footer>{opensAt && closesAt && <span className="preference-window"><Clock3 />{t("classes.preferences.available", { start: format(opensAt), end: format(closesAt) })}</span>}{submitted && <button type="button" className="button button--secondary" onClick={() => { setDecision(data.student.decision); setDestinations(data.student.decision === "move" ? data.student.destinations : []); setNotes(data.student.notes || ""); setEditing(false); }}><X />{t("classes.preferences.cancelEdit")}</button>}<button type="button" className="button button--primary" onClick={() => void save()} disabled={locked || saving}><Send />{saving ? t("classes.preferences.submitting") : submitted ? t("classes.preferences.saveVersion") : t("classes.preferences.submit")}</button></footer>
    </>}
  </section></>;
}
