/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {Check,Filter,LoaderCircle,Ticket,Trash2} from "lucide-react";
import {AppShell} from "@/components/app-shell";
import {AuthGuard} from "@/components/auth-guard";
type Row={id:string;class_id:number;request_type:string|null;description:string;status:string;response:string|null;student_name:string|null;student_number:string|null;created_by_name:string;created_at:number;execution_result:string|null};
const labels:Record<string,string>={pending:"Pendente",approved:"Aprovado",rejected:"Recusado",executed:"Executado",execution_error:"Erro de execução"};
const types:Record<string,string>={reopen:"Reabrir turma",add_student:"Adicionar estudante",remove_student:"Remover estudante",replace_student:"Substituir estudante",correct_student:"Corrigir dados",other:"Outro pedido"};
export function TicketAdmin(){
 const [rows,setRows]=useState<Row[]>([]),[filter,setFilter]=useState("active"),[saving,setSaving]=useState<string|null>(null),[notice,setNotice]=useState("");
 const load=useCallback(async()=>{const response=await fetch("/api/admin/class-tickets",{cache:"no-store"}),result=await response.json() as {tickets:Row[]};setRows(result.tickets||[])},[]);
 useEffect(()=>{void load()},[load]);
 const visible=useMemo(()=>rows.filter(row=>filter==="all"||(filter==="active"?["pending","approved"].includes(row.status):filter==="resolved"?["executed","rejected"].includes(row.status):row.status===filter)),[rows,filter]);
 const update=(id:string,patch:Partial<Row>)=>setRows(current=>current.map(row=>row.id===id?{...row,...patch}:row));
 async function save(row:Row){setSaving(row.id);const response=await fetch("/api/admin/class-tickets",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:row.id,status:row.status,response:row.response})}),result=await response.json() as {error?:string};setNotice(response.ok?"Decisão guardada e executada quando aplicável.":result.error||"Não foi possível atualizar.");setSaving(null);if(response.ok)void load()}
 async function remove(row:Row){if(!window.confirm("Apagar definitivamente este ticket? O evento ficará registado no histórico."))return;setSaving(row.id);const response=await fetch("/api/admin/class-tickets",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id:row.id})}),result=await response.json() as {error?:string};setNotice(response.ok?"Ticket apagado.":result.error||"Não foi possível apagar.");setSaving(null);if(response.ok)void load()}
 return <AuthGuard><AppShell active="tickets" breadcrumb="Pedidos"><section className="page-heading"><div><span className="eyebrow">Gestão administrativa</span><h1>Pedidos de alteração</h1><p>As aprovações seguras são executadas automaticamente e ficam auditadas.</p></div></section><section className="panel"><div className="panel__header"><div><h2>Todos os pedidos</h2><p>{rows.filter(row=>["pending","approved"].includes(row.status)).length} pendentes · {rows.filter(row=>["executed","rejected"].includes(row.status)).length} resolvidos</p></div><label className="select-field"><Filter/><select value={filter} onChange={event=>setFilter(event.target.value)}><option value="active">Pendentes</option><option value="resolved">Resolvidos</option><option value="all">Todos</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>{notice&&<p className="admin-notice">{notice}</p>}<div className="ticket-admin-list">{visible.map(row=><article key={row.id} className="ticket-admin-card"><header><span><Ticket/>Turma {row.class_id}</span><time>{new Date(row.created_at).toLocaleString("pt-PT")}</time></header><h3>{types[row.request_type||"other"]||"Pedido de alteração"}</h3><small>{row.student_number||`Criado por ${row.created_by_name}`}</small><p>{row.description}</p>{row.execution_result&&<p>{row.execution_result}</p>}<label>Decisão<select value={row.status} disabled={["executed","rejected"].includes(row.status)} onChange={event=>update(row.id,{status:event.target.value})}><option value="pending">Pendente</option><option value="approved">Aprovar e executar</option><option value="rejected">Recusar</option>{["executed","execution_error"].includes(row.status)&&<option value={row.status}>{labels[row.status]}</option>}</select></label><label>Fundamentação<textarea value={row.response||""} onChange={event=>update(row.id,{response:event.target.value})}/></label><div className="ticket-card-actions"><button className="button button--secondary button--danger" disabled={saving===row.id} onClick={()=>void remove(row)}><Trash2/>Apagar</button><button className="button button--primary" disabled={saving===row.id||["executed","rejected"].includes(row.status)} onClick={()=>void save(row)}>{saving===row.id?<LoaderCircle className="spin"/>:<Check/>}Guardar decisão</button></div></article>)}{!visible.length&&<div className="empty-state">Não existem pedidos com este filtro.</div>}</div></section></AppShell></AuthGuard>
}
