"use client";
import Link from "next/link";
import {useCallback,useEffect,useRef,useState} from "react";
import {ArrowDown,ArrowLeft,ArrowRight,ArrowUp,Check,Plus,Save,Send,Trash2,UsersRound,X} from "lucide-react";
import {AppShell} from "@/components/app-shell";
import type {Turma} from "@/data/turmas";
type Student={id:string;nome:string;numero:string;preferencia:"Ficar"|"Mudar";isSelf:boolean;destinations:number[]};
type Detail={class:{id:number;status:string;submittedAt:number|null;workflowStep:number;draftRevision:number};students:Student[];settings:{openAt:string;closeAt:string};serverNow:number;permissions:{edit:boolean;manage:boolean;representative:boolean}};
type Row={id:string;fullName:string;studentNumber:string;preference:"stay"|"move"};
const blank=():Row=>({id:crypto.randomUUID(),fullName:"",studentNumber:"",preference:"stay"});
const steps=["Preenchimento","Verificação e edição","Revisão e submissão"];
const requestTypes={reopen:"Reabrir a turma para edição",add_student:"Adicionar um estudante",remove_student:"Remover um estudante",replace_student:"Substituir um estudante",correct_student:"Corrigir dados de um estudante",other:"Outro pedido"};
export function TurmaDetail({turma}:{turma:Turma;alunosIniciais:unknown[]}){
 const [data,setData]=useState<Detail|null>(null),[rows,setRows]=useState<Row[]>([blank()]),[step,setStep]=useState(1),[saveState,setSaveState]=useState("idle"),[notice,setNotice]=useState(""),[confirming,setConfirming]=useState(false),[submitting,setSubmitting]=useState(false),[requestType,setRequestType]=useState("reopen"),[description,setDescription]=useState(""),[ticketStudentId,setTicketStudentId]=useState(""),[ticketName,setTicketName]=useState(""),[ticketNumber,setTicketNumber]=useState(""),[ticketPreference,setTicketPreference]=useState<"stay"|"move">("stay"),[destinations,setDestinations]=useState<number[]>([]);
 const revision=useRef(0),loaded=useRef(false),abort=useRef<AbortController|null>(null),lastPayload=useRef("");
 const load=useCallback(async()=>{const response=await fetch(`/api/classes/${turma.id}`,{cache:"no-store"}),next=await response.json() as Detail&{error?:string};if(!response.ok){setNotice(next.error||"Não foi possível carregar a turma.");return}setData(next);setStep(next.class.workflowStep||1);revision.current=next.class.draftRevision||0;const restored=next.students.map(s=>({id:s.id,fullName:s.nome,studentNumber:s.numero,preference:s.preferencia==="Mudar"?"move" as const:"stay" as const})),initial=restored.length?restored:[blank()];setRows(initial);setDestinations(next.students.find(s=>s.isSelf)?.destinations||[]);setTimeout(()=>{loaded.current=true;lastPayload.current=JSON.stringify({students:initial,workflowStep:next.class.workflowStep||1})},0)},[turma.id]);
 // A leitura assíncrona inicializa o estado remoto da página.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load()},[load]);
 const save=useCallback(async(nextRows:Row[],nextStep:number,force=false)=>{if(!data?.permissions.edit)return true;const key=JSON.stringify({students:nextRows,workflowStep:nextStep});if(!force&&key===lastPayload.current)return true;abort.current?.abort();const controller=new AbortController();abort.current=controller;setSaveState("saving");const nextRevision=Math.max(Date.now(),revision.current+1);try{const response=await fetch(`/api/classes/${turma.id}/draft`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({students:nextRows,workflowStep:nextStep,revision:nextRevision}),signal:controller.signal}),result=await response.json() as {error?:string;revision?:number};if(!response.ok)throw new Error(result.error);revision.current=result.revision||nextRevision;lastPayload.current=key;setSaveState("saved");return true}catch(error){if(error instanceof DOMException&&error.name==="AbortError")return false;setSaveState("error");setNotice(error instanceof Error?error.message:"Não foi possível guardar.");return false}},[data?.permissions.edit,turma.id]);
 useEffect(()=>{if(!loaded.current||!data?.permissions.edit)return;const timer=window.setTimeout(()=>void save(rows,step),900);return()=>window.clearTimeout(timer)},[rows,step,save,data?.permissions.edit]);
 const update=(id:string,patch:Partial<Row>)=>setRows(current=>current.map(row=>row.id===id?{...row,...patch}:row));
 async function go(next:number){if(await save(rows,next,true)){setStep(next);window.scrollTo({top:0,behavior:"smooth"})}}
 async function submit(){setSubmitting(true);if(await save(rows,3,true)){const response=await fetch(`/api/classes/${turma.id}/submit`,{method:"POST"}),result=await response.json() as {error?:string};setNotice(response.ok?"Turma submetida com sucesso.":result.error||"Não foi possível submeter.");if(response.ok){setConfirming(false);await load()}}setSubmitting(false)}
 async function ticket(){const payload={studentId:ticketStudentId||undefined,fullName:ticketName||undefined,studentNumber:ticketNumber||undefined,preference:ticketPreference};const response=await fetch(`/api/classes/${turma.id}/tickets`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({requestType,description,payload})}),result=await response.json() as {error?:string};setNotice(response.ok?"Pedido enviado ao Núcleo de Gestão.":result.error||"Não foi possível enviar.");if(response.ok){setDescription("");setTicketStudentId("");setTicketName("");setTicketNumber("")}}
 async function savePreferences(){const response=await fetch("/api/student/destinations",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({destinations})}),result=await response.json() as {error?:string};setNotice(response.ok?"A tua decisão foi guardada.":result.error||"Não foi possível guardar.")}
 if(!data)return <AppShell active="turmas" breadcrumb={turma.nome}><p className="empty-state">A carregar turma…</p></AppShell>;
 const submitted=!['draft','reopened'].includes(data.class.status),own=data.students.find(s=>s.isSelf),afterDeadline=data.serverNow>=Date.parse(data.settings.closeAt);
 return <AppShell active="turmas" breadcrumb={turma.nome} currentClassId={turma.id}><Link className="back-link" href="/"><ArrowLeft/>Voltar às turmas</Link><section className="detail-heading"><div><span className="eyebrow">2.º ano · 2026/2027</span><h1>{turma.nome}</h1><p>{rows.filter(row=>row.fullName||row.studentNumber).length} estudantes</p></div><span className="status status--neutral">{submitted?"Submetida":"Rascunho"}</span></section>{notice&&<p className="admin-notice" role="status">{notice}</p>}
 {data.permissions.edit&&<><ol className="class-progress">{steps.map((name,index)=><li key={name} className={step===index+1?"is-active":step>index+1?"is-complete":""}><button type="button" disabled><span>{step>index+1?<Check/>:index+1}</span>{name}</button></li>)}</ol><p className={`autosave autosave--${saveState}`} aria-live="polite">{saveState==="saving"?"A guardar…":saveState==="error"?"Não foi possível guardar":saveState==="saved"?"Alterações guardadas":"Rascunho guardado na base de dados"}</p></>}
 {data.permissions.edit&&step===1&&<section className="panel class-editor"><div className="panel__header"><div><h2>{step===1?"Adicionar estudantes":"Verificar e editar"}</h2><p>{step===1?"Pode adicionar vários estudantes antes de continuar.":`${rows.length} estudantes no rascunho.`}</p></div><div className="student-add-actions"><button className="button button--secondary" onClick={()=>setRows(current=>[...current,...Array.from({length:5},blank)])}><UsersRound/>Adicionar 5 estudantes</button><button className="button button--secondary" onClick={()=>setRows(current=>[...current,blank()])}><Plus/>Adicionar estudante</button></div></div><div className="student-blocks">{rows.map((row,index)=><article className="student-block" key={row.id}><header><strong>Estudante {index+1}</strong><button aria-label={`Remover estudante ${index+1}`} onClick={()=>setRows(current=>current.length===1?[blank()]:current.filter(item=>item.id!==row.id))}><Trash2/></button></header><div><label>Nome completo<input value={row.fullName} onChange={e=>update(row.id,{fullName:e.target.value})}/></label><label>Número mecanográfico<input inputMode="numeric" maxLength={9} placeholder="202500000" value={row.studentNumber} onChange={e=>update(row.id,{studentNumber:e.target.value.replace(/\D/g,"")})}/></label><label>Indicação do representante<select value={row.preference} onChange={e=>update(row.id,{preference:e.target.value as "stay"|"move"})}><option value="stay">Pretende ficar</option><option value="move">Pretende mudar</option></select></label></div></article>)}</div><footer className="batch-footer"><span/><button className="button button--primary" onClick={()=>void go(step+1)}><Save/>Guardar e continuar<ArrowRight/></button></footer></section>}
 {data.permissions.edit&&step===2&&<section className="panel class-editor verification-list-panel"><div className="panel__header"><div><h2>Lista de estudantes</h2><p>Para adicionar ou editar estudantes, volta ao preenchimento.</p></div></div><div className="table-scroll"><table><thead><tr><th>Estudante</th><th>Número mecanográfico</th><th>Indicação do representante</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.fullName||"—"}</td><td>{row.studentNumber||"—"}</td><td>{row.preference==="stay"?"Pretende ficar":"Pretende mudar"}</td></tr>)}</tbody></table></div><footer className="batch-footer"><button className="button button--secondary" onClick={()=>void go(1)}><ArrowLeft/>Voltar para editar</button><button className="button button--primary" onClick={()=>void go(3)}>Continuar para submissão<ArrowRight/></button></footer></section>}
 {data.permissions.edit&&step===3&&<section className="panel"><div className="panel__header"><div><h2>Submissão da turma</h2><p>Confirma a composição final antes de submeter.</p></div></div><p className="submission-warning" role="alert"><strong>Atenção:</strong> Após submeter a turma, só será possível voltar atrás através de um pedido ao Núcleo de Gestão da CC. Erros deste tipo devem ser evitados a todo o custo.</p><div className="table-scroll"><table><thead><tr><th>Estudante</th><th>Número mecanográfico</th><th>Indicação</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.fullName}</td><td>{row.studentNumber}</td><td>{row.preference==='stay'?'Pretende ficar':'Pretende mudar'}</td></tr>)}</tbody></table></div><footer className="batch-footer"><button className="button button--secondary" onClick={()=>void go(2)}>Voltar e corrigir</button><button className="button button--primary" onClick={()=>setConfirming(true)}><Send/>Submeter turma</button></footer></section>}
 {submitted&&<section className="panel"><div className="panel__header"><div><h2>Composição submetida</h2><p>A edição direta está bloqueada.</p></div></div><div className="table-scroll"><table><thead><tr><th>Estudante</th><th>Número mecanográfico</th><th>Indicação inicial</th></tr></thead><tbody>{data.students.map(s=><tr key={s.id}><td>{s.nome}{s.isSelf?' (tu)':''}</td><td>{s.numero}</td><td>{s.preferencia}</td></tr>)}</tbody></table></div></section>}
 {submitted&&data.permissions.representative&&<section className="panel ticket-panel"><h2>Pedido de alteração</h2><p>Indica apenas os dados necessários. O Núcleo de Gestão decide e a execução fica registada.</p><label>Tipo<select value={requestType} onChange={e=>setRequestType(e.target.value)}>{Object.entries(requestTypes).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{["remove_student","replace_student","correct_student"].includes(requestType)&&<label>Estudante afetado<select value={ticketStudentId} onChange={e=>setTicketStudentId(e.target.value)}><option value="">Selecionar estudante</option>{data.students.map(student=><option key={student.id} value={student.id}>{student.nome} · {student.numero}</option>)}</select></label>}{["add_student","replace_student","correct_student"].includes(requestType)&&<div className="ticket-structured-fields"><label>{requestType==="correct_student"?"Nome corrigido":"Nome do novo estudante"}<input value={ticketName} onChange={e=>setTicketName(e.target.value)}/></label><label>Número mecanográfico<input inputMode="numeric" maxLength={9} placeholder="202500000" value={ticketNumber} onChange={e=>setTicketNumber(e.target.value.replace(/\D/g,""))}/></label>{requestType!=="correct_student"&&<label>Indicação<select value={ticketPreference} onChange={e=>setTicketPreference(e.target.value as "stay"|"move")}><option value="stay">Pretende ficar</option><option value="move">Pretende mudar</option></select></label>}</div>}{requestType==="reopen"&&<p className="admin-notice">Ao aprovar, a turma volta a rascunho e poderá ser editada novamente.</p>}<label>Motivo<textarea minLength={10} value={description} onChange={e=>setDescription(e.target.value)}/></label><button className="button button--primary" onClick={()=>void ticket()}>Enviar pedido</button></section>}
 {submitted&&own&&afterDeadline&&<section className="panel destination-editor"><h2>Foste inscrito na Turma {turma.id}</h2><p>O representante indicou que pretendes {own.preferencia==='Ficar'?'permanecer nesta turma':'mudar de turma'}.</p><div className="decision-actions"><button onClick={()=>setDestinations([])}>Permanecer nesta turma</button><button onClick={()=>setDestinations(current=>current.length?current:[turma.id===1?2:1])}>Quero indicar preferências de mudança</button></div>{destinations.length>0&&<><p>Podes indicar apenas as alternativas que te interessam, por ordem. Existem até 19 alternativas; a tua turma atual é sempre a opção de segurança, perfazendo 20 resultados possíveis.</p><p>As preferências não garantem a mudança. Se nenhuma for possível, permanecerás na turma atual.</p><div className="preference-list">{destinations.map((destination,index)=><div className="preference-row" key={destination}><strong>{index+1}.ª</strong><label><span className="sr-only">Turma da {index+1}.ª preferência</span><select value={destination} onChange={e=>setDestinations(current=>current.map((value,i)=>i===index?Number(e.target.value):value))}>{Array.from({length:20},(_,i)=>i+1).filter(id=>id!==turma.id&&(!destinations.includes(id)||id===destination)).map(id=><option key={id} value={id}>Turma {id}</option>)}</select></label><div className="preference-order"><button aria-label={`Subir a ${index+1}.ª preferência`} disabled={index===0} onClick={()=>setDestinations(current=>current.map((value,i)=>i===index-1?current[index]:i===index?current[index-1]:value))}><ArrowUp/></button><button aria-label={`Descer a ${index+1}.ª preferência`} disabled={index===destinations.length-1} onClick={()=>setDestinations(current=>current.map((value,i)=>i===index+1?current[index]:i===index?current[index+1]:value))}><ArrowDown/></button><button aria-label={`Remover a ${index+1}.ª preferência`} onClick={()=>setDestinations(current=>current.filter((_,i)=>i!==index))}><X/></button></div></div>)}</div><button className="button button--secondary" disabled={destinations.length>=19} onClick={()=>setDestinations(current=>[...current,Array.from({length:20},(_,i)=>i+1).find(id=>id!==turma.id&&!current.includes(id))!])}><Plus/>Acrescentar preferência</button></>}<button className="button button--primary" onClick={()=>void savePreferences()}>Guardar decisão</button></section>}
 {confirming&&<div className="modal-backdrop"><div className="confirm-dialog" role="dialog" aria-modal="true"><h2>Confirmar submissão</h2><p>Tem a certeza de que pretende submeter esta turma? Depois da submissão, a composição deixa de poder ser alterada diretamente pelo representante. Qualquer alteração posterior terá de ser solicitada à administração.</p><div><button className="button button--secondary" onClick={()=>setConfirming(false)} disabled={submitting}>Cancelar</button><button className="button button--primary" onClick={()=>void submit()} disabled={submitting}>Confirmar submissão</button></div></div></div>}
 </AppShell>;
}
