export type RankingPeriod = "week" | "month" | "all";
export type QuizBadge = { id: string; title: string; description: string; earned: boolean };
export type QuizLevel = { level: number; title: string; xp: number; levelStartXp: number; nextLevelXp: number; progress: number };
export type QuizGameProfile = QuizLevel & {
  streakDays: number;
  bestStreakDays: number;
  practisedToday: boolean;
  todayCompleted: number;
  dailyGoal: number;
  completedCount: number;
  passedTotal: number;
  passedThisWeek: number;
  badges: QuizBadge[];
};
export const QUIZ_TIME_ZONE: string;
export const RANKING_THRESHOLD: number;
export const DAILY_GOAL: number;
export const XP_PER_CORRECT: number;
export const XP_PASS_BONUS: number;
export const XP_PERFECT_BONUS: number;
export const RANKING_PERIODS: RankingPeriod[];
export function quizDayKey(timestamp: number): string;
export function zonedMidnight(year: number, month: number, day: number): number;
export function rankingPeriodStart(period: string, now?: number): number | null;
export function isRankingPass(correctCount: number, questionCount: number): boolean;
export function attemptXp(correctCount: number, questionCount: number): number;
export function quizLevel(xp: number): QuizLevel;
export function quizGameProfile(attempts: Array<{ completedAt: number; questionCount: number; correctCount: number }>, now?: number): QuizGameProfile;
export function normaliseRankingName(value: unknown): string | null;
export function suggestedRankingName(fullName: string): string;
export function rankRows<T extends { passedCount: number }>(rows: T[]): Array<T & { rank: number }>;
