import type { StudentSpecialStatus } from "@/lib/student-status";

export type TestPersona="admin"|"stay"|"move-a"|"move-b"|"special";
export const TEST_PERSONAS=[
 {id:"admin" as const,name:"Administrador de teste",role:"admin" as const,classId:null,email:"admin.teste@up.pt"},
 {id:"stay" as const,name:"Ana Martins",role:"student" as const,classId:1,email:"up202600001@up.pt"},
 {id:"move-a" as const,name:"Bruno Costa",role:"student" as const,classId:2,email:"up202600002@up.pt"},
 {id:"move-b" as const,name:"Carla Sousa",role:"student" as const,classId:4,email:"up202600003@up.pt"},
 {id:"special" as const,name:"Joana Ferreira",role:"student" as const,classId:1,email:"up202600006@up.pt"},
];
type TestStudent={id:string;full_name:string;student_number:string;class_id:number;student_decision:string|null;special_status?:StudentSpecialStatus};
type TestAnnouncement={id:string;title:string;body:string;priority:string;status:string;author_name:string;author_position_label:string;authorId?:string;authorEmail?:string;authorStudentNumber?:string;published_at:number;expires_at:number|null};
type TestUnit={id:string;code:string;name:string;ects:number;year:number;semester:number;representativeUserId:string};
type TestState={version:number;windows:Array<{group:number;classes:string;openAt:string;closeAt:string}>;decisions:Record<string,number[]>;proposalStatus:string|null;roster?:TestStudent[];announcements:TestAnnouncement[];units:TestUnit[]};
const defaults:TestState={version:3,windows:[{group:1,classes:"1–2",openAt:"2026-07-15T08:00:00.000Z",closeAt:"2026-07-17T19:00:00.000Z"},{group:2,classes:"3–5",openAt:"2026-07-16T08:00:00.000Z",closeAt:"2026-07-18T19:00:00.000Z"}],decisions:{stay:[],"move-a":[1,3],"move-b":[5,3],"t1-move":[2,4],"t2-move":[3,1],"t3-move":[4,5],"t4-move":[2,5],"t5-move":[1,3]},proposalStatus:null,announcements:[{id:"test-announcement",title:"Bem-vindos ao ambiente de testes",body:"Este comunicado urgente usa apenas dados fictícios e pode ser alterado em segurança.",priority:"urgent",status:"published",author_name:"Administrador de teste",author_position_label:"Administrador Principal",published_at:Date.now(),expires_at:null}],units:[{id:"test-unit-anatomy",code:"ANAT2",name:"Anatomia II",ects:7.5,year:2,semester:1,representativeUserId:"admin"}]};
const roster=[
 {id:"stay",full_name:"Ana Martins",student_number:"202600001",class_id:1,student_decision:"stay"},
 {id:"t1-stay-2",full_name:"Beatriz Lopes",student_number:"202600004",class_id:1,student_decision:"stay"},
 {id:"t1-move",full_name:"Gonçalo Neves",student_number:"202600005",class_id:1,student_decision:"move"},
 {id:"special",full_name:"Joana Ferreira",student_number:"202600006",class_id:1,student_decision:null,special_status:"worker_student" as const},
 {id:"t1-stay-3",full_name:"Luís Correia",student_number:"202600007",class_id:1,student_decision:"stay"},
 {id:"move-a",full_name:"Bruno Costa",student_number:"202600002",class_id:2,student_decision:"move"},
 {id:"t2-stay-1",full_name:"Mariana Alves",student_number:"202600008",class_id:2,student_decision:"stay"},
 {id:"t2-move",full_name:"Nuno Carvalho",student_number:"202600009",class_id:2,student_decision:"move"},
 {id:"t2-pending",full_name:"Rita Faria",student_number:"202600010",class_id:2,student_decision:null,special_status:"athlete" as const},
 {id:"t2-stay-2",full_name:"Tiago Ramos",student_number:"202600011",class_id:2,student_decision:"stay"},
 {id:"t3-stay-1",full_name:"Diana Ribeiro",student_number:"202600012",class_id:3,student_decision:"stay"},
 {id:"t3-move",full_name:"Eduardo Lima",student_number:"202600013",class_id:3,student_decision:"move"},
 {id:"t3-stay-2",full_name:"Filipa Melo",student_number:"202600014",class_id:3,student_decision:"stay"},
 {id:"t3-pending",full_name:"Henrique Sousa",student_number:"202600015",class_id:3,student_decision:null,special_status:"other" as const},
 {id:"t3-stay-3",full_name:"Inês Rocha",student_number:"202600016",class_id:3,student_decision:"stay"},
 {id:"move-b",full_name:"Carla Sousa",student_number:"202600003",class_id:4,student_decision:"move"},
 {id:"t4-stay-1",full_name:"Leonor Pinto",student_number:"202600017",class_id:4,student_decision:"stay"},
 {id:"t4-move",full_name:"Miguel Cardoso",student_number:"202600018",class_id:4,student_decision:"move"},
 {id:"t4-pending",full_name:"Patrícia Gomes",student_number:"202600019",class_id:4,student_decision:null},
 {id:"t4-stay-2",full_name:"Rodrigo Cunha",student_number:"202600020",class_id:4,student_decision:"stay"},
 {id:"t5-stay-1",full_name:"Sofia Matos",student_number:"202600021",class_id:5,student_decision:"stay"},
 {id:"t5-move",full_name:"Tomás Vieira",student_number:"202600022",class_id:5,student_decision:"move"},
 {id:"t5-stay-2",full_name:"Vera Monteiro",student_number:"202600023",class_id:5,student_decision:"stay"},
 {id:"t5-pending",full_name:"Afonso Leal",student_number:"202600024",class_id:5,student_decision:null},
 {id:"t5-stay-3",full_name:"Catarina Reis",student_number:"202600025",class_id:5,student_decision:"stay"},
];
let installed=false,realFetch:typeof fetch|null=null;
export function testModeEnabled(){return typeof window!=="undefined"&&localStorage.getItem("gu-test-mode")==="1"}
export function testPersona(){return (typeof window!=="undefined"?localStorage.getItem("gu-test-persona"):null) as TestPersona||"admin"}
export function setTestMode(active:boolean){if(active){localStorage.setItem("gu-test-mode","1");localStorage.setItem("gu-test-persona","admin");if(!localStorage.getItem("gu-test-state"))localStorage.setItem("gu-test-state",JSON.stringify(defaults))}else{localStorage.removeItem("gu-test-mode");localStorage.removeItem("gu-test-persona")}window.dispatchEvent(new Event("gu-test-mode"))}
export function setTestPersona(persona:TestPersona){localStorage.setItem("gu-test-persona",persona);window.location.assign("/")}
function state():TestState{try{const saved=JSON.parse(localStorage.getItem("gu-test-state")||"");return saved.version===defaults.version?{...defaults,...saved}:structuredClone(defaults)}catch{return structuredClone(defaults)}}
function saveState(next:TestState){localStorage.setItem("gu-test-state",JSON.stringify(next))}
function reply(value:unknown,status=200){return new Response(JSON.stringify(value),{status,headers:{"content-type":"application/json"}})}
function excelXml(value:unknown){return String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;")}
function testExcel(rows:TestStudent[],decisions:Record<string,number[]>){
 const cell=(value:unknown,style="Default")=>`<Cell ss:StyleID="${style}"><Data ss:Type="String">${excelXml(value)}</Data></Cell>`;
 const headers=["Nome","Número mecanográfico","Turma atual","Decisão","Preferências"];
 const body=rows.map(row=>`<Row>${cell(row.full_name)}${cell(row.student_number)}${cell(`Turma ${row.class_id}`)}${cell(row.student_decision==="move"?"Mudar":row.student_decision==="stay"?"Ficar":"Sem decisão")}${cell((decisions[row.id]||[]).map(id=>`Turma ${id}`).join(" → "))}</Row>`).join("");
 return `<?xml version="1.0" encoding="UTF-8"?><?mso-application progid="Excel.Sheet"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet" xmlns:x="urn:schemas-microsoft-com:office:excel"><Styles><Style ss:ID="Default"><Alignment ss:Vertical="Center"/><Font ss:FontName="Aptos" ss:Size="10"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#E6E2D8"/></Borders></Style><Style ss:ID="Title"><Font ss:Bold="1" ss:Size="16" ss:Color="#FFFFFF"/><Interior ss:Color="#171714" ss:Pattern="Solid"/></Style><Style ss:ID="Header"><Font ss:Bold="1" ss:Color="#171714"/><Interior ss:Color="#F6C945" ss:Pattern="Solid"/><Alignment ss:Vertical="Center"/></Style></Styles><Worksheet ss:Name="Colocações"><Table><Column ss:Width="190"/><Column ss:Width="110"/><Column ss:Width="90"/><Column ss:Width="90"/><Column ss:Width="260"/><Row ss:Height="30">${cell("Gestor Universitário — ambiente de testes","Title")}<Cell ss:MergeAcross="3" ss:StyleID="Title"><Data ss:Type="String">Dados exclusivamente fictícios</Data></Cell></Row><Row ss:Height="24">${headers.map(value=>cell(value,"Header")).join("")}</Row>${body}</Table><AutoFilter x:Range="R2C1:R${rows.length+2}C5"/><WorksheetOptions><FreezePanes/><FrozenNoSplit/><SplitHorizontal>2</SplitHorizontal><TopRowBottomPane>2</TopRowBottomPane></WorksheetOptions></Worksheet></Workbook>`;
}
function studentShape(row:TestStudent){const specialStatus="none" as const;return {id:row.id,nome:row.full_name,numero:row.student_number,preferencia:row.student_decision==="move"?"Mudar":row.student_decision==="stay"?"Ficar":"A aguardar decisão",isSelf:row.id===testPersona(),destinations:state().decisions[row.id]||[],specialStatus}}
async function mock(input:RequestInfo|URL,init?:RequestInit):Promise<Response|null>{const raw=typeof input==="string"?input:input instanceof URL?input.pathname:input.url,url=new URL(raw,location.origin),path=url.pathname,method=(init?.method||"GET").toUpperCase(),s=state(),r:TestStudent[]=s.roster||roster,persona=TEST_PERSONAS.find(item=>item.id===testPersona())||TEST_PERSONAS[0];
 if(path==="/api/config")return reply({maintenanceMode:false,closeAt:"2020-01-01T00:00:00.000Z",serverNow:Date.now(),testMode:true});
 if(path==="/api/modules"&&method==="GET")return reply({modules:[
  {key:"classes",enabled:true,effectiveEnabled:true,submodules:[{key:"classes.rosters",enabled:true,effectiveEnabled:true},{key:"classes.preferences",enabled:true,effectiveEnabled:true},{key:"classes.placements",enabled:true,effectiveEnabled:true},{key:"classes.special_statuses",enabled:false,effectiveEnabled:false}]},
  {key:"announcements",enabled:true,effectiveEnabled:true,submodules:[{key:"announcements.feed",enabled:true,effectiveEnabled:true},{key:"announcements.publishing",enabled:true,effectiveEnabled:true}]},
  {key:"curricular_units",enabled:true,effectiveEnabled:true,submodules:[{key:"curricular_units.catalog",enabled:true,effectiveEnabled:true},{key:"curricular_units.management",enabled:true,effectiveEnabled:true},{key:"curricular_units.detail",enabled:true,effectiveEnabled:true}]},
  {key:"calendar",enabled:true,effectiveEnabled:true,submodules:[{key:"calendar.events",enabled:true,effectiveEnabled:true},{key:"calendar.management",enabled:true,effectiveEnabled:true}]},
  {key:"documents",enabled:true,effectiveEnabled:true,submodules:[{key:"documents.library",enabled:true,effectiveEnabled:true},{key:"documents.management",enabled:true,effectiveEnabled:true}]},
  {key:"requests",enabled:true,effectiveEnabled:true,submodules:[{key:"requests.submission",enabled:true,effectiveEnabled:true},{key:"requests.management",enabled:true,effectiveEnabled:true}]},
  {key:"directory",enabled:true,effectiveEnabled:true,submodules:[{key:"directory.members",enabled:true,effectiveEnabled:true}]},
  {key:"polls",enabled:true,effectiveEnabled:true,submodules:[{key:"polls.voting",enabled:true,effectiveEnabled:true},{key:"polls.management",enabled:true,effectiveEnabled:true}]},
  {key:"dashboard",enabled:true,effectiveEnabled:true,homepageEligible:true,submodules:[{key:"dashboard.personal",enabled:true,effectiveEnabled:true},{key:"dashboard.analytics",enabled:true,effectiveEnabled:true}]},
  {key:"search",enabled:true,effectiveEnabled:true,submodules:[{key:"search.global",enabled:true,effectiveEnabled:true}]},
  {key:"materials",enabled:true,effectiveEnabled:true,submodules:[{key:"materials.library",enabled:true,effectiveEnabled:true},{key:"materials.submission",enabled:true,effectiveEnabled:true},{key:"materials.moderation",enabled:true,effectiveEnabled:true}]}
 ],home:{configuredModuleKey:null,resolvedModuleKey:"dashboard",href:"/dashboard",mode:"automatic"}});
 if(path==="/api/announcements"&&method==="GET")return reply({announcements:s.announcements.filter(item=>item.status==="published").map(item=>persona.role==="admin"?{...item,authorId:item.authorId||"admin",authorEmail:item.authorEmail||"up202507850@up.pt",authorStudentNumber:item.authorStudentNumber||"202507850"}:item),canPublish:persona.role==="admin",canViewAuthorIdentifiers:persona.role==="admin",publishingEnabled:true});
 if(path==="/api/announcements"&&method==="POST"){if(persona.role!=="admin")return reply({error:"A publicação está reservada a membros da Comissão de Curso."},403);const body=JSON.parse(String(init?.body||"{}")),announcement:TestAnnouncement={id:crypto.randomUUID(),title:String(body.title||""),body:String(body.body||""),priority:String(body.priority||"normal"),status:"published",author_name:persona.name,author_position_label:"Administrador Principal",authorId:persona.id,authorEmail:"up202507850@up.pt",authorStudentNumber:"202507850",published_at:Date.now(),expires_at:body.expiresAt?Date.parse(String(body.expiresAt)):null};s.announcements=[announcement,...s.announcements];saveState(s);return reply({ok:true,id:announcement.id},201)}
 if(path==="/api/announcements"&&method==="PATCH"){const body=JSON.parse(String(init?.body||"{}"));s.announcements=s.announcements.map(item=>item.id===body.id?{...item,status:"archived"}:item);saveState(s);return reply({ok:true})}
 if(path==="/api/admin/curricular-units"&&method==="GET"){if(persona.role!=="admin")return reply({error:"Acesso reservado ao Núcleo de Gestão."},403);return reply({units:s.units,representatives:[{id:"admin",fullName:"Administrador de teste",email:"admin.teste@up.pt",commissionPosition:"Administrador Principal"}]})}
 if(path==="/api/admin/curricular-units"&&["POST","PUT"].includes(method)){if(persona.role!=="admin")return reply({error:"Acesso reservado ao Núcleo de Gestão."},403);const body=JSON.parse(String(init?.body||"{}")),unit:TestUnit={id:String(body.id||crypto.randomUUID()),code:String(body.code||""),name:String(body.name||""),ects:Number(body.ects),year:Number(body.year),semester:Number(body.semester),representativeUserId:String(body.representativeUserId||"")};s.units=method==="POST"?[...s.units,unit]:s.units.map(item=>item.id===unit.id?unit:item);saveState(s);return reply({ok:true,id:unit.id},method==="POST"?201:200)}
 if(path==="/api/admin/users"&&method==="GET")return reply({users:TEST_PERSONAS.map(item=>({id:item.id,email:item.email,full_name:item.name,role:item.role,admin_override:item.role==="admin"?1:0,class_representative:0,represented_class:null,status:"active",status_reason:null,status_until:null,commission_position:item.role==="admin"?"principal_admin":null,commission_department:item.role==="admin"?"management":null,email_verified_at:Date.now(),last_login_at:Date.now(),created_at:Date.now(),updated_at:Date.now()})),positions:[{code:"principal_admin",label:"Administrador Principal",authority_level:"supreme",rank:1}],departments:[{code:"management",label:"Gestão",rank:1}]});
 if(path==="/api/admin/users"&&method==="PATCH")return reply({ok:true});
 if(path==="/api/admin/audit"&&method==="GET")return reply({entries:[]});
 if(path==="/api/admin/class-tickets"&&["GET","PATCH","DELETE"].includes(method))return reply(method==="GET"?{tickets:[]}: {ok:true});
 if(path==="/api/search"&&method==="GET"){const query=(url.searchParams.get("q")||"").trim().toLocaleLowerCase("pt-PT"),results:Array<{id:string;type:string;title:string;description:string;href:string}>=[],academicResults=[{id:"test-event-anatomy",type:"event",title:"Frequência de Anatomia II",description:"Evento do calendário académico",href:"/calendario"},{id:"test-material-anatomy",type:"material",title:"Resumo fictício de Anatomia II",description:"Material de estudo",href:"/materiais"},{id:"test-unit-anatomy",type:"curricular_unit",title:"Anatomia II",description:"7,5 ECTS · 2.º ano",href:"/unidades-curriculares/test-unit-anatomy"}];results.push(...academicResults.filter(item=>`${item.title} ${item.description}`.toLocaleLowerCase("pt-PT").includes(query)));for(let classId=1;classId<=5;classId++){const title=`Turma ${classId}`;if(query&&title.toLocaleLowerCase("pt-PT").includes(query))results.push({id:String(classId),type:"class",title,description:`${r.filter(row=>row.class_id===classId).length} estudantes`,href:`/turmas/${classId}`})}return reply({results});}
 if(path==="/api/admin/settings"&&method==="GET")return reply({maintenanceMode:false,maintenanceMessage:"",preferenceWindows:s.windows,testMode:true});
 if(path==="/api/admin/settings"&&method==="PUT"){const body=JSON.parse(String(init?.body||"{}"));if(body.section==="preference_windows")s.windows=body.windows.map((item:{openAt:string;closeAt:string},i:number)=>({...item,group:i+1,classes:i?"3–5":"1–2"}));saveState(s);return reply({ok:true})}
 if(path==="/api/classes"&&method==="GET")return reply({classes:Array.from({length:5},(_,i)=>({id:i+1,status:s.proposalStatus==="published"?"published":i===4?"draft":"submitted",submitted_at:i===4&&s.proposalStatus!=="published"?null:Date.now(),representative:"Comissão de Curso",students:r.filter(row=>row.class_id===i+1).length,stays:r.filter(row=>row.class_id===i+1&&row.student_decision==="stay").length,moves:r.filter(row=>row.class_id===i+1&&row.student_decision==="move").length}))});
 if(path==="/api/classes/import"&&method==="POST"){const body=JSON.parse(String(init?.body||"{}")),students=Array.isArray(body.students)?body.students:[],accepted=students.filter((student:{codigo_estatuto:string})=>String(student.codigo_estatuto).toUpperCase()==="N"),skipped=students.length-accepted.length;if(accepted.some((student:{n_mecanografico:string})=>r.some(row=>row.student_number===student.n_mecanografico)))return reply({error:"O CSV contém um estudante já existente."},409);s.roster=[...r,...accepted.map((student:{turma:number;nome:string;n_mecanografico:string})=>({id:crypto.randomUUID(),full_name:student.nome,student_number:student.n_mecanografico,class_id:Number(student.turma),student_decision:null,special_status:"none" as const}))];saveState(s);return reply({ok:true,imported:accepted.length,skipped,classes:[...new Set(accepted.map((student:{turma:number})=>Number(student.turma)))]})}
 const detail=path.match(/^\/api\/classes\/(\d+)$/);if(detail&&method==="GET"){const id=Number(detail[1]);return reply({class:{id,status:id===5?"draft":"submitted"},students:r.filter(row=>row.class_id===id).map(studentShape),permissions:{edit:persona.role==="admin"},settings:{}})}
 const classSave=path.match(/^\/api\/classes\/(\d+)\/save$/);if(classSave&&method==="PUT"){const classId=Number(classSave[1]),body=JSON.parse(String(init?.body||"{}")),students=Array.isArray(body.students)?body.students:[];s.roster=[...r.filter(row=>row.class_id!==classId),...students.map((student:{id?:string;fullName:string;studentNumber:string;specialStatus?:StudentSpecialStatus})=>{const existing=r.find(row=>row.student_number===student.studentNumber),specialStatus=student.specialStatus||"none";return {id:existing?.id||student.id||crypto.randomUUID(),full_name:student.fullName,student_number:student.studentNumber,class_id:classId,student_decision:specialStatus==="none"?existing?.student_decision||null:null,special_status:specialStatus}})];saveState(s);return reply({ok:true})}
 if(path==="/api/student/destinations"&&method==="GET"){const row=r.find(item=>item.id===persona.id);if(!row)return reply({error:"Perfil sem estudante."},403);const window=s.windows[row.class_id<=2?0:1],specialStatus="none",decision=row.student_decision==="move"?"move":row.student_decision==="stay"?"stay":null;return reply({student:{classId:row.class_id,decision,submittedAt:decision?Date.now():null,notes:"",destinations:decision==="move"?s.decisions[row.id]||[]:[],specialStatus,canSubmitPreferences:true},activeClasses:[1,2,3,4,5],settings:{preferencesOpenAt:window.openAt,preferencesCloseAt:window.closeAt,groupLabel:`Turmas ${window.classes}`},serverNow:Date.now()})}
 if(path==="/api/student/destinations"&&method==="PUT"){const body=JSON.parse(String(init?.body||"{}")),decision=String(body.decision||""),requested=Array.isArray(body.destinations)?body.destinations.map(Number):[];if(decision!=="stay"&&decision!=="move")return reply({error:"Escolhe se pretendes manter a turma ou mudar."},400);if(decision==="move"&&!requested.length)return reply({error:"Indica pelo menos uma turma de destino antes de submeter."},400);s.decisions[persona.id]=decision==="move"?requested:[];s.roster=r.map(row=>row.id===persona.id?{...row,student_decision:decision}:row);saveState(s);return reply({ok:true,submittedAt:Date.now()})}
 if(path==="/api/admin/distribution-check")return reply({ready:true,checkedAt:Date.now(),summary:{classes:5,students:r.length,blockers:0,warnings:0,automaticStays:r.filter(row=>!row.student_decision).length,exceptionalPending:0},checks:[{key:"roster",label:"Turmas e estudantes",description:"Turmas submetidas, não vazias e identificadores válidos.",status:"passed",count:0},{key:"preferences",label:"Preferências",description:"Decisões e destinos ativos, únicos e ordenados.",status:"passed",count:0},{key:"review",label:"Informação adicional",description:"Informação confidencial classificada pela CC.",status:"passed",count:0},{key:"simulation",label:"Equilíbrio e cálculo",description:"Pré-visualização concluída e limites respeitados.",status:"passed",count:0}],issues:[],simulation:{possible:true,moved:Object.values(s.decisions).filter(values=>values.length).length,manualReviews:0,randomized:0,classCounts:Object.fromEntries(Array.from({length:5},(_,index)=>[index+1,r.filter(row=>row.class_id===index+1).length]))}});
 if(path==="/api/admin/placements"&&method==="GET")return reply({students:r.map(row=>({...row,preference_source:row.student_decision?"student":"automatic",preference_admin_reason:null,notes:null,considerations:"[]",exception_points:0,exception_reviewed_at:null,exception_review_reason:null,additional_info_validation:null,additional_info_validation_note:null,additional_info_review_status:null,distribution_result:null})),destinations:Object.entries(s.decisions).flatMap(([id,values])=>values.map((destination_class,rank)=>({student_id:id,destination_class,rank:rank+1}))),activeClasses:[1,2,3,4,5]});
 if(path==="/api/admin/placements"&&method==="PATCH")return reply({ok:true,status:JSON.parse(String(init?.body||"{}")).status});
 if(path==="/api/admin/placements"&&method==="PUT"){const body=JSON.parse(String(init?.body||"{}")),id=String(body.studentId||""),decision=String(body.decision||""),student=r.find(row=>row.id===id),requested=decision==="move"&&Array.isArray(body.destinations)?body.destinations.map(Number):[],validationTypes=Array.isArray(body.validationTypes)?body.validationTypes.map(String):[],preferenceChanged=student?.student_decision!==decision||JSON.stringify(s.decisions[id]||[])!==JSON.stringify(requested);if((preferenceChanged||validationTypes.includes("other"))&&!String(body.reason||"").trim())return reply({error:"A justificação administrativa é obrigatória para esta alteração."},400);if(decision!=="stay"&&decision!=="move")return reply({error:"Selecione se o estudante mantém a turma ou pretende mudar."},400);if(decision==="move"&&!requested.length)return reply({error:"Indique pelo menos uma preferência para um estudante que pretende mudar."},400);s.decisions[id]=requested;s.roster=r.map(row=>row.id===id?{...row,student_decision:decision}:row);s.proposalStatus=null;saveState(s);return reply({ok:true})}
 if(path==="/api/admin/export-validation"&&method==="GET")return new Response(testExcel(r,s.decisions),{headers:{"content-type":"application/vnd.ms-excel; charset=utf-8","content-disposition":"attachment; filename=colocacoes-ambiente-teste.xls"}})
 if(path==="/api/admin/distribution-proposals"&&method==="GET"){const results=r.map(row=>{const preferred=s.decisions[row.id]?.[0],moves=Boolean(row.student_decision==="move"&&preferred);return {studentId:row.id,originClass:row.class_id,destinationClass:moves?preferred:row.class_id,rank:moves?1:null,status:moves?"moved":"stayed_by_choice",points:0,manualReview:false}});return reply({proposals:s.proposalStatus?[{id:"test-proposal",status:s.proposalStatus,result_snapshot:JSON.stringify(results),created_at:Date.now()}]:[]})}
 if(/^\/api\/admin\/distribution-proposals\//.test(path)&&method==="POST"){const action=path.split("/").pop();if(action!=="calculate"&&!s.proposalStatus)return reply({error:"Calcula primeiro uma proposta."},409);if(action==="apply")s.roster=r.map(row=>row.student_decision==="move"&&s.decisions[row.id]?.[0]?{...row,class_id:s.decisions[row.id][0]}:row);s.proposalStatus=action==="calculate"?"draft":action==="approve"?"approved":action==="apply"?"applied":action==="publish"?"published":action==="rollback"?"applied":s.proposalStatus;saveState(s);return reply(action==="calculate"?{ok:true,status:"draft",proposal:{id:"test-proposal"}}:{ok:true,status:s.proposalStatus,placementsPreserved:action==="rollback"||undefined})}
 return null}
export function installTestApi(){if(installed||typeof window==="undefined")return;installed=true;realFetch=window.fetch.bind(window);window.fetch=async(input,init)=>testModeEnabled()?(await mock(input,init))||realFetch!(input,init):realFetch!(input,init)}
